### ISSUE TITLE
SinonFakeServer.respondWith not working with query params on 17.0.2

### ISSUE THREAD

**Issue by 1bberto** [sinonjs/sinon#2596] opened 2024-05-07 20:28 UTC
**Describe the bug**
the `respondWith` seems to not work when the URL has a `?`

**To Reproduce**

I have this 
```typescript
const url =  `/api/FakeApi?hash=10101050&fakeData=true&isGet=true`;

const method = 'GET';

const response = [
  status,
  { 'Content-type': 'application/json', ...headers },
  JSON.stringify(body),
];

server.respondWith(method, url, response);
```

the code is breaking when `server.respondWith` is being called

the error is 
```
TypeError: Unexpected MODIFIER at 12, expected END
at mustConsume (webpack://my-company/./node_modules/sinon/pkg/sinon-esm.js?:19288:15)
at parse (webpack://sensei/./node_modules/sinon/pkg/sinon-esm.js?:19346:9)
at stringToRegexp (webpack://my-company/./node_modules/sinon/pkg/sinon-esm.js?:19503:27)
at pathToRegexp (webpack://my-company/./node_modules/sinon/pkg/sinon-esm.js?:19581:12)
at Object.respondWith (webpack://my-company/./node_modules/sinon/pkg/sinon-esm.js?:17830:57)
```

**Context (please complete the following information):**

- Sinon version : *17.0.2*
- Runtime: Node *v20.11.1*, Chrome Headless 124.0.6367.119 (Windows 10)

**Comment by itchyny** [comment] 2024-05-10 08:21
We've been blocked by this issue, too. I noticed that the issue is caused by https://github.com/sinonjs/nise/pull/216. Rewriting all the usages of `respondWith` is a pain for us, but reading https://github.com/sinonjs/nise/pull/216, this seems to be an intended breaking change.

**Comment by fatso83** [comment] 2024-05-10 16:00
Thanks for providing this. This bug is totally on me. I am not sure how I missed James' very detailed explanations in his PR, which spells out how this is a breaking change and actually asks for input (which I also missed, must have been late).

My suggestion:
- Update the NPM registry to point to 17.0.1 as latest and 17.0.2 as deprecated
- Add support to Nise for re-writing expressions including query parameters to the new form through a compatibility flag
- Make a patch version of Sinon 17 use that flag by default to restore current behavior
- Release Sinon 18 with that flag disabled and note the requirement in the docs, but with the possibility of enabling it manually to avoid rewriting expressions

Thoughts, @43081j  or @mroderick ?

**Comment by 43081j** [comment] 2024-05-13 21:29
i think that makes sense. let me know if you want any help sorting the new flag out etc

doesn't sound too difficult. basically default it to legacy behaviour which auto-escapes  `?` under the hood

**Comment by fatso83** [comment] 2024-05-15 12:12
The code repro is unfortunately not runnable, so I have no 100% assurance this is fixed, but it _should_ be fixed in the changes James shipped to Nise (enabling the legacy routes flag by default) should mean this is gone. Please test Sinon 18 and report back if this is not fixed.

**Closed by fatso83** 2024-05-15 12:12 UTC
Labels: Bug, Unverified
