### ISSUE TITLE
callCount not working with promises

### ISSUE THREAD

**Issue by andre-batista-ww** [sinonjs/sinon#957] opened 2015-12-23 03:05 UTC
Hello friends, thanks for the great library!

I ran into an issue and I believe it is a bug, below is a sample unit test that should pass AFAIU, but it does not. I stubbed fn1 and fn2, and that seems to work successfully because the fullfilledWith assertion is passing, however I'd expect fn2's call count to be 1(the fact that fulfilledWith(333) passes proves that it was called), but Sinon says it's 0 :( Am I missing something or is this a real bug?

Any clarification will be much appreciated.

Thanks in advance!
- Andre

CODE:
```

'use strict';

var should = require('should');
var sinon = require('sinon');
require('should-sinon');
var q = require('q');


var testService = {
  fn1: function() {return q.resolve(111);},
  fn2: function() {return q.resolve(222)},
  fn3: function() {
    var self = this;
    return self.fn1()
      .fail(function(e) {
        return self.fn2();
      });
  }
};


describe('test testService', function() {
  beforeEach(function(done) {
    sinon.stub(testService, 'fn1', function() {
      return q.reject();
    });
    sinon.stub(testService, 'fn2', function() {
      return q.resolve(333);
    });
    done();
  });

  afterEach(function() {
    testService.fn1.restore();
    testService.fn2.restore();
  });

  it('fn1 and fn2 should have call count of 1', function() {
    var p = testService.fn3(); 

    return q.all([
      p.should.be.Promise(),
      p.should.be.fulfilledWith(333),
      testService.fn1.should.have.callCount(1),
      testService.fn2.should.have.callCount(1)
    ]);
  });

});


```

CONSOLE:

```

Running "mochaTest:exerciseServiceTests" (mochaTest) task


  test testService
    1) fn1 and fn2 should have call count of 1


  0 passing (20ms)
  1 failing

  1) test testService fn1 and fn2 should have call count of 1:
     expected Function {
  alwaysCalledOn: Function { name: '' },
  alwaysCalledWith: Function { name: '' },
  alwaysCalledWithExactly: Function { name: '' },
  alwaysCalledWithMatch: Function { name: '' },
  alwaysCalledWithNew: Function { name: '' },
  alwaysReturned: Function { name: '' },
  alwaysThrew: Function { name: '' },
  args: Array [],
  callArg: Function { name: '' },
  callArgOn: Function { name: '' },
  callArgOnWith: Function { name: '' },
  callArgWith: Function { name: '' },
  callCount: 0,
  callIds: Array [],
  called: false,
  calledAfter: Function { name: 'calledAfter' },
  calledBefore: Function { name: 'calledBefore' },
  calledOn: Function { name: '' },
  calledOnce: false,
  calledThrice: false,
  calledTwice: false,
  calledWith: Function { name: '' },
  calledWithExactly: Function { name: '' },
  calledWithMatch: Function { name: '' },
  calledWithNew: Function { name: '' },
  displayName: 'fn2',
  exceptions: Array [],
  firstCall: null,
  formatters: Object {
    '*': Function { name: '' },
    C: Function { name: '' },
    c: Function { name: '' },
    n: Function { name: '' },
    t: Function { name: '' }
  },
  getCall: Function { name: 'getCall' },
  getCalls: Function { name: '' },
  id: 'spy#1',
  instantiateFake: Function { name: 'create' },
  invoke: Function { name: 'invoke' },
  invokeCallback: Function { name: '' },
  isSinonProxy: true,
  lastCall: null,
  matches: Function { name: '' },
  named: Function { name: 'named' },
  neverCalledWith: Function { name: '' },
  neverCalledWithMatch: Function { name: '' },
  notCalled: true,
  printf: Function { name: '' },
  reset: Function { name: '' },
  restore: Function { sinon: true, name: '' },
  returnValues: Array [],
  returned: Function { name: '' },
  secondCall: null,
  spyCall: Function { toString: Function { name: '' }, name: 'createSpyCall' },
  stackTrace: 'Error: Stack Trace for original\n  at Object.wrapMethod (/shared/activity-tracking/app/node_modules/sinon/lib/sinon/util/core.js:140:34)\n  at Object.stub (/shared/activity-tracking/app/node_modules/sinon/lib/sinon/stub.js:67:26)\n  at Context.<anonymous> (/shared/activity-tracking/app/server/tests/services/exerciseService.spec.js:27:11)\n  at Hook.Runnable.run (/shared/activity-tracking/app/node_modules/mocha/lib/runnable.js:233:15)\n  at next (/shared/activity-tracking/app/node_modules/mocha/lib/runner.js:271:10)\n  at Immediate._onImmediate (/shared/activity-tracking/app/node_modules/mocha/lib/runner.js:292:5)\n  at processImmediate [as _immediateCallback] (timers.js:367:17)\n',
  stacks: Array [],
  thirdCall: null,
  thisValues: Array [],
  threw: Function { name: '' },
  toString: Function { name: 'toString' },
  withArgs: Function { name: '' },
  yield: Function { name: '' },
  yieldOn: Function { name: '' },
  yieldTo: Function { name: '' },
  yieldToOn: Function { name: '' },
  name: 'proxy'
} to be called once but was called 0 times
  AssertionError: expected Function {
    alwaysCalledOn: Function { name: '' },
    alwaysCalledWith: Function { name: '' },
    alwaysCalledWithExactly: Function { name: '' },
    alwaysCalledWithMatch: Function { name: '' },
    alwaysCalledWithNew: Function { name: '' },
    alwaysReturned: Function { name: '' },
    alwaysThrew: Function { name: '' },
    args: Array [],
    callArg: Function { name: '' },
    callArgOn: Function { name: '' },
    callArgOnWith: Function { name: '' },
    callArgWith: Function { name: '' },
    callCount: 0,
    callIds: Array [],
    called: false,
    calledAfter: Function { name: 'calledAfter' },
    calledBefore: Function { name: 'calledBefore' },
    calledOn: Function { name: '' },
    calledOnce: false,
    calledThrice: false,
    calledTwice: false,
    calledWith: Function { name: '' },
    calledWithExactly: Function { name: '' },
    calledWithMatch: Function { name: '' },
    calledWithNew: Function { name: '' },
    displayName: 'fn2',
    exceptions: Array [],
    firstCall: null,
    formatters: Object {
      '*': Function { name: '' },
      C: Function { name: '' },
      c: Function { name: '' },
      n: Function { name: '' },
      t: Function { name: '' }
    },
    getCall: Function { name: 'getCall' },
    getCalls: Function { name: '' },
    id: 'spy#1',
    instantiateFake: Function { name: 'create' },
    invoke: Function { name: 'invoke' },
    invokeCallback: Function { name: '' },
    isSinonProxy: true,
    lastCall: null,
    matches: Function { name: '' },
    named: Function { name: 'named' },
    neverCalledWith: Function { name: '' },
    neverCalledWithMatch: Function { name: '' },
    notCalled: true,
    printf: Function { name: '' },
    reset: Function { name: '' },
    restore: Function { sinon: true, name: '' },
    returnValues: Array [],
    returned: Function { name: '' },
    secondCall: null,
    spyCall: Function { toString: Function { name: '' }, name: 'createSpyCall' },
    stacks: Array [],
    thirdCall: null,
    thisValues: Array [],
    threw: Function { name: '' },
    toString: Function { name: 'toString' },
    withArgs: Function { name: '' },
    yield: Function { name: '' },
    yieldOn: Function { name: '' },
    yieldTo: Function { name: '' },
    yieldToOn: Function { name: '' },
    name: 'proxy'
  } to be called once but was called 0 times
    at Context.<anonymous> (server/tests/services/exerciseService.spec.js:45:35)
    at Context.<anonymous> (server/tests/services/exerciseService.spec.js:30:5)




Warning: Task "mochaTest:exerciseServiceTests" failed. Use --force to continue.

```

**Comment by fatso83** [comment] 2016-01-06 09:32
I have used a minute trying to look at this, but this is way too much details obscuring what is going on. The essentials of the issue is buried into the sinon-should library, anyway, and your report might as well go there.

I am closing it as it is too unclear as where/what is going wrong.

Feel free to reopen the case if you manage to pinpoint any bug to Sinon. Right now it might as well be in the unassociated helper library or in user code.

**Closed by fatso83** 2016-01-06 09:32 UTC
