### ISSUE TITLE
Add documentation for how to stub ES6 module dependencies

### ISSUE THREAD

**Issue by gajus** [sinonjs/sinon#1358] opened 2017-03-22 23:00 UTC
It is a common use case to mock ES modules.

e.g. I have a module that imports `getEventByEventId`

```js
import getEventByEventId from '../queries/getEventByEventId';

export default async (
  {
    connection,
    session
  }: ResolverContextType
) => {
  if (!session || !session.userId) {
    throw new Error('User must be authenticated.');
  }

  const event = await getEventByEventId(connection, eventId);

  // ..
}

```

In my test I want to mock `getEventByEventId`, e.g.

```js
import test from 'ava';
import sinon from 'sinon';
import moment from 'moment';
import createReservation from '../../../src/mutators/createReservation';

test('throws an error if the event is in the past', async (t) => {
  const parameters: any = {};

  const context: any = {
    session: {
      userId: 1
    }
  };

  const stub = sinon.stub().returns({
    date: moment().format('YYYY-MM-DD'),
    time: moment(new Date().getTime() - 1000 * 60).format('HH:mm')
  });

  // How to use the stub to mock `getEventByEventId`?

  await t.throws(createReservation(context), 'Cannot create a reservation for a past event.');
});

```

**Comment by gajus** [comment] 2017-03-22 23:01
To contribute to my own question, the only way I found this to work is by using [`babel-plugin-rewire`](https://github.com/speedskater/babel-plugin-rewire), e.g.

```js
import test from 'ava';
import sinon from 'sinon';
import moment from 'moment';
import createReservation from '../../../src/mutators/createReservation';

test('throws an error if the event is in the past', async (t) => {
  const parameters: any = {};

  const context: any = {
    session: {
      userId: 1
    }
  };

  const stub = sinon.stub().returns({
    date: moment().format('YYYY-MM-DD'),
    time: moment(new Date().getTime() - 1000 * 60).format('HH:mm')
  });

  createReservation.__Rewire__('getEventByEventId', stub);

  await t.throws(createReservation(context), 'Cannot create a reservation for a past event.');
});

```

This solution is far from ideal, though. For one, it breaks the Flow type annotations.

**Comment by gajus** [comment] 2017-03-22 23:05
One way to improve a DX would be to provide an ability to define a getter method when stubbing an object, e.g.

```js
const stub = sinon.stub(createReservation, '__Rewire__', 'getEventByEventId');

```

which would be equivalent to:

```js
const stub = sinon.stub();

createReservation.__Rewire__('getEventByEventId', stub);

```

**Comment by gajus** [comment] 2017-03-22 23:11
I've solved this locally by creating an ad-hoc helper for rewiring the dependencies:

```js
const rewire = (module: any, methodName: string, method) => {
  module.__Rewire__(methodName, method);

  return method;
};

```

which I am then using like this:

```js
rewire(createReservation, 'getEventByEventId', sinon.stub())
  .returns({
    date: moment().format('YYYY-MM-DD'),
    time: moment(new Date().getTime() - 1000 * 60).format('HH:mm')
  });

```

**Comment by fatso83** [comment] 2017-03-23 14:34
Duplicate of #1121

**Closed by fatso83** 2017-03-23 14:34 UTC

**Comment by fatso83** [comment] 2017-03-23 14:39
@gajus please see the pointers in #1121. I have tried covering the various strategies for doing this in the comments linked from that.

**Comment by chenzhutian** [comment] 2017-09-12 05:44
I think @gajus talked about stubing ES6 module dependence rather than stub ES6 class.
May be #1458 is related.

**Comment by zhenyulin** [comment] 2018-01-23 14:15
proxyquire looks like a good choice for this case @gajus , as the function is imported as a module

**Comment by whawker** [comment] 2018-05-24 09:06
This may be old news, but I do this

```js
import * as myDependency from './some/other/file'

beforeEach(function () {
  this.mySpy = sinon.spy(myDependency, 'default');
});
```

**Comment by theKashey** [comment] 2019-03-19 04:09
It's a bad idea to use `sinon` to `spy` or `stub` into a dependency, while all you need is to `mock` it.
`Proxyquire`, `jest.mock` or `rewiremock` would be the only right solutions for module-level dependency mocking.

**Comment by mroderick** [comment] 2019-03-19 08:09
We even have a guide on [How to use Link Seams with CommonJS](https://sinonjs.org/how-to/link-seams-commonjs/).
