### ISSUE TITLE
Sinon 1.17.0: sinon.createStubInstance cannot be used twice on the same constructor

### ISSUE THREAD

**Issue by mantoni** [sinonjs/sinon#852] opened 2015-09-24 12:08 UTC
This is a new issue in Sinon 1.17.0 and it's working fine with 1.16.1:

```js
var a = sinon.createStubInstance((MyThing);
var b = sinon.createStubInstance((MyThing);
```

Fails on the second line with:

```
TypeError: Attempted to wrap constructor which is already wrapped
  at checkWrappedMethod (node_modules/sinon/lib/sinon/util/core.js:91)
  at wrapMethod (node_modules/sinon/lib/sinon/util/core.js:121)
  at stub (node_modules/sinon/lib/sinon/stub.js:66)
  at node_modules/sinon/lib/sinon/stub.js:59
  at node_modules/sinon/lib/sinon/walk.js:34
  at forEach (null:null)
  at walk (node_modules/sinon/lib/sinon/walk.js:35)
  at walk (node_modules/sinon/lib/sinon/walk.js:39)
  at walk (node_modules/sinon/lib/sinon/walk.js:39)
  at stub (node_modules/sinon/lib/sinon/stub.js:61)
  at node_modules/sinon/lib/sinon/util/core.js:361
  ...
```

Environment: Node 4.0.0

**Comment by fatso83** [comment] 2015-09-24 20:57
I am unable to recreate this? Tried running it with everything from 1.16.1 to the latest `master`
```
describe('issue #852', function() {
    function MyThing() {}
    it('should not fail', function() {
        var a = sinon.createStubInstance(MyThing);
        var b = sinon.createStubInstance(MyThing);
    });
});
```

**Comment by fatso83** [comment] 2015-09-24 21:10
Tried this in Node 0.12 and 4.1, as well as PhantomJS. Never a failing test.

**Comment by mantoni** [comment] 2015-09-24 21:15
Sorry, left this here without further investigating. Had a hell of a day. I have a large test case that has this issue. Will see if I can extract the gist of it tomorrow.

**Comment by flexfrank** [comment] 2015-09-25 07:45
Creating a stub of a subclass reproduces the same error.

~~~JavaScript
describe('', function() {
    var A = function() {};
    var B = function() {};
    B.prototype = Object.create(A.prototype);
    B.prototype.constructor = A;

    it('create stub instance of a subclass', function() {
        var b = sinon.createStubInstance(B);
    });
});
~~~

~~~
  ✗ create stub instance of a subclass
	TypeError: Attempted to wrap constructor which is already wrapped
	    at checkWrappedMethod (node_modules/sinon/pkg/sinon.js:1239)
	    at wrapMethod (node_modules/sinon/pkg/sinon.js:1269)
	    at stub (node_modules/sinon/pkg/sinon.js:3322)
	    at node_modules/sinon/pkg/sinon.js:3315
	    at node_modules/sinon/pkg/sinon.js:3220


PhantomJS 1.9.8 (Linux 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.012 secs / 0.001 secs)
~~~

sinon 1.17.0
node v0.12.6

**Comment by fatso83** [comment] 2015-09-25 07:53
Cool, running git bisect tests now to find the regression.

**Comment by fatso83** [comment] 2015-09-25 07:58
This is a duplicate of #847, so closing this one. Do follow progress on the other.

**Closed by fatso83** 2015-09-25 07:58 UTC

**Comment by mroderick** [comment] 2015-09-26 05:49
Sinon.JS v1.17.1 is now on npm, the website will be updated soon.

**Comment by kmiyashiro** [comment] 2015-10-01 19:46
I'm still getting this error on 1.17.1

**Comment by fatso83** [comment] 2015-10-01 21:24
@kmiyashiro that's surprising. Certainly not using the test case above? Do you have a consistent way of reproducing the bug so that it's possible to verify?

**Comment by kmiyashiro** [comment] 2015-10-01 22:16
Not using the test case and I do not have a reduced test case. I was using `sinon.createStubInstance(Router)` where `Router` is something that extends a subclass of `Backbone.Router` using backbone's `Backbone.Router.extend`. I tried creating a fiddle, but I can't seem to find an https origin that hosts 1.17.1.
```js
var BaseRouter = Backbone.Router.extend(...);
var Router = BaseRouter.extend(...);
sinon.createStubInstance(Router);
```
