### ISSUE TITLE
sinon.stub(object, "missingMethod") silently fails

### ISSUE THREAD

**Issue by tsclaus** [sinonjs/sinon#1552] opened 2017-09-07 17:57 UTC
* Sinon version : 2.3.8
* Environment : Node.js 6.9.5
* Example URL : N/A
* Other libraries you are using: Karma

**What did you expect to happen?**

I expected sinon to either throw an error immediately or stub the method despite it not existing yet (I think the first one is better to make errors due to typos more obvious).

**What actually happens**

Essentially nothing. `object.missingMethod` is undefined after the call but the call doesn't error either.

**How to reproduce**

```
'use strict';

const sinon = require('sinon')

describe('stub for missing method', function() {
  beforeEach(function() {
    this.test = {};

    sinon.stub(this.test, 'foo');
  });

  it('should exist if it didn\'t error in the beforeEach', function() {
    this.test.foo();

    sinon.assert.calledOnce(this.test.foo);
  });
});
```

The test will break on `this.test.foo()` since it is still undefined. My sinon version is outdated, but looking at `function stub(object, property)`, it seems this would also be an issue in the newest version. EDIT: Looking closer, I don't think is a problem in 3.X. If you don't fix old versions and can't reproduce this in 3.X, this issue is irrelevant.

If this is indeed an issue, I will try to address it along with the other issue I have open this weekend.

**Comment by fatso83** [comment] 2017-09-08 08:01
Please verify if this is a problem using the latest sinon version. Just do `npm install sinon@latest` and run those tests again. This is related to #1512 and #1537

**Comment by tsclaus** [comment] 2017-09-08 16:26
The test still fails with 3.2.1, specifically with:
```
stub for missing method should exist if it didn't error in the beforeEach:
     TypeError: this.test.foo is not a function
      at Context.<anonymous> (test.spec.js:13:15)
```

**Comment by fatso83** [comment] 2017-09-12 15:35
Thanks for the report! This is verified to be a duplicate of #1508. You can track progress there.

**Closed by fatso83** 2017-09-12 15:35 UTC

**Comment by fatso83** [comment] 2017-09-18 15:19
Fixed.
