### ISSUE TITLE
Lolex not loading correctly

### ISSUE THREAD

**Issue by seaneagan** [sinonjs/sinon#621] opened 2014-12-03 16:04 UTC
Sinon version : 1.12.1 Environment : karma

Bug description

Getting this error which seems to be related to aeb9b08ce1c5f238e606e84656ed52b29e8d8aa0:

INFO [PhantomJS 1.9.8 (Windows 7)]: Connected on socket EnuKfnpvFllf1Phw3qI- wit                                                                                                                                   h id 47894035
PhantomJS 1.9.8 (Windows 7) polls getCurrentMonth FAILED
        TypeError: 'undefined' is not an object (evaluating '_lolex.install')
            at C:/eclipse/tact/eclipse4.3_x64/workspace_Trunk/museum-mobile/muse                                                                                                                                   um-mobile-web-admin/src/main/webapp/node_modules/sinon/lib/sinon/util/fake_timer                                                                                                                                   s.js:39
            at C:/eclipse/tact/eclipse4.3_x64/workspace_Trunk/museum-mobile/muse                                                                                                                                   um-mobile-web-admin/src/main/webapp/js/test/polls.tests.js:3
            at C:/eclipse/tact/eclipse4.3_x64/workspace_Trunk/museum-mobile/muse                                                                                                                                   um-mobile-web-admin/src/main/webapp/node_modules/karma-jasmine/lib/adapter.js:16                                                                                                                                   6
            at http://localhost:9876/karma.js:189
            at http://localhost:9876/context.html:55
PhantomJS 1.9.8 (Windows 7): Executed 1 of 1 (1 FAILED) ERROR (0.009 secs / 0.00                                                                                                                                   6 secs)
INFO [Chrome 39.0.2171 (Windows 7)]: Connected on socket P5hBguDcC2sbloEm3qI_ wi                                                                                                                                   PhantomJS 1.9.8 (Windows 7): Executed 1 of 1 (1 FAILED) ERROR (0.009 secs / 0.00                                                                                                                                   Chrome 39.0.2171 (Windows 7) polls getCurrentMonth FAILED
        TypeError: Cannot read property 'install' of undefined
            at Object.sinon.useFakeTimers (C:/eclipse/tact/eclipse4.3_x64/worksp                                                                                                                                   ace_Trunk/museum-mobile/museum-mobile-web-admin/src/main/webapp/node_modules/sin                                                                                                                                   on/lib/sinon/util/fake_timers.js:39:31)
            at null.<anonymous> (C:/eclipse/tact/eclipse4.3_x64/workspace_Trunk/                                                                                                                                   museum-mobile/museum-mobile-web-admin/src/main/webapp/js/test/polls.tests.js:3:2                                                                                                                                   1)
PhantomJS 1.9.8 (Windows 7): Executed 1 of 1 (1 FAILED) ERROR (0.009 secs / 0.00                                                                                                                                   PhantomJS 1.9.8 (Windows 7): Executed 1 of 1 (1 FAILED) ERROR (0.009 secs / 0.00                                                                                                                                   6 secs)
Chrome 39.0.2171 (Windows 7): Executed 1 of 1 (1 FAILED) ERROR (0.012 secs / 0.0                                                                                                                                   09 secs)
PhantomJS 1.9.8 (Windows 7): Executed 1 of 1 (1 FAILED) ERROR (0.009 secs / 0.00                                                                                                                                   6 secs)
Firefox 31.0.0 (Windows 7) polls getCurrentMonth FAILED
        TypeError: _lolex is undefined in C:/eclipse/tact/eclipse4.3_x64/workspa                                                                                                                                   ce_Trunk/museum-mobile/museum-mobile-web-admin/src/main/webapp/node_modules/sino                                                                                                                                   n/lib/sinon/util/fake_timers.js (line 39)
        makeApi/sinon.useFakeTimers@C:/eclipse/tact/eclipse4.3_x64/workspace_Tru                                                                                                                                   nk/museum-mobile/museum-mobile-web-admin/src/main/webapp/node_modules/sinon/lib/                                                                                                                                   sinon/util/fake_timers.js:39:17
        @C:/eclipse/tact/eclipse4.3_x64/workspace_Trunk/museum-mobile/museum-mob                                                                                                                                   ile-web-admin/src/main/webapp/js/test/polls.tests.js:3:7
        createStartFn/<@C:/eclipse/tact/eclipse4.3_x64/workspace_Trunk/museum-mo                                                                                                                                   bile/museum-mobile-web-admin/src/main/webapp/node_modules/karma-jasmine/lib/adap                                                                                                                                   ter.js:166:5
        [2]</Karma/this.loaded@http://localhost:9876/karma.js:189:7
        @http://localhost:9876/context.html:55:5

PhantomJS 1.9.8 (Windows 7): Executed 1 of 1 (1 FAILED) ERROR (0.009 secs / 0.00                                                                                                                                   6 secs)
PhantomJS 1.9.8 (Windows 7): Executed 1 of 1 (1 FAILED) ERROR (0.009 secs / 0.00                                                                                                                                   6 secs)
Chrome 39.0.2171 (Windows 7): Executed 1 of 1 (1 FAILED) ERROR (0.012 secs / 0.0                                                                                                                                   09 secs)
Firefox 31.0.0 (Windows 7): Executed 1 of 1 (1 FAILED) ERROR (0.006 secs / 0.001                                                                                                                                    secs)
{ [Error: karma exited with code 1]
  plugin: 'gulp-karma',
  showStack: false,
  message: 'karma exited with code 1' }

**Comment by asharma-r7** [comment] 2015-01-06 11:35
With sinon v1.12.1 +, I'm seeing this error with Grunt:

>> Error: scripterror: Illegal path or script error: ['lolex'] at
>> _SpecRunner.html:21 
>> .grunt/grunt-contrib-jasmine/require.js:12 v
>> .grunt/grunt-contrib-jasmine/require.js:30 

When I drop down to v1.12.0 sinon gets loaded accordingly. So if you guys can make do without the features from v1.12.1+ for now until the issue is resolved, you can also trying dropping to v1.12.0.

**Comment by mroderick** [comment] 2015-01-20 21:50
@seaneagan  Thank you for reporting this :cactus: 

Would you mind trying to reproduce this with 1.12.2?

**Comment by riddla** [comment] 2015-02-02 15:13
I'm getting the same error with the `1.12.2` version.

**Comment by webPapaya** [comment] 2015-06-29 06:59
I'm having the same issue on chrome 43 using sinon 1.15.0. Is there any workaround?

**Comment by danielmanesku** [comment] 2015-07-07 12:11
I am having the same issue with 1.15.0 with mocha. 
fake_timers.js (line 39)::sinon.useFakeTimers = function () { :: var clock = llx.install(now || 0, methods);
fails bacause llx.install is not defined.
Downgrading to 1.12 is not an option for me, because I am hit by #714 and/or #711 .

**Comment by timkindberg** [comment] 2015-10-27 19:49
`1.12.2` did not fix this for me either.

**Comment by fatso83** [comment] 2015-10-28 09:11
If anyone could supply a working code example (Gist, repo, ... ) that displays this error with 1.17.2 it would make looking into fixing it a lot more attractive. I have yet to see this error myself.

**Comment by Radagaisus** [comment] 2015-11-12 12:23
I think I just ran into this issue. I was using sinon 1.12.2 (with konacha and and konacha-chai-matchers). Manually upgrading to the latest version (1.17.2) fixed this.

**Comment by fatso83** [comment] 2015-11-13 07:24
I am closing this issue after seeing @Radagaisus comment. Regarded as fixed.

**Closed by fatso83** 2015-11-13 07:24 UTC
Labels: 1.x, AMD, Help wanted

**Comment by mghaderyan-nisum-com** [comment] 2016-05-03 17:41
This is happening even in version 1.17.3. None of the above worked for me. Is it really fixed?

**Comment by fatso83** [comment] 2016-05-03 20:04
@mghaderyan-nisum-com As I wrote earlier in the thread: 
> If anyone could supply a working code example (Gist, repo, ... ) that displays this error with 1.17.2 it would make looking into fixing it a lot more attractive. I have yet to see this error myself.

Could you make a runnable example where this fails?

**Comment by anneFly** [comment] 2016-05-19 08:50
@mghaderyan-nisum-com I had the same bug in `1.17.3`. Upgrading to `1.17.4` fixed it for me.

**Comment by mghaderyan-nisum-com** [comment] 2016-05-19 16:20
Thanks I will try that.

**Comment by chrismllr** [comment] 2016-07-09 03:57
Seeing a similar version of this bug, getting this error:
`undefined is not an object (evaluating 'llx.install')`

Anyone having similar issues?

All (relevant?) packages and their versions:
```
"chai": "^3.4.1",
"karma": "^0.13.21",
"mocha": "^2.2.5",
"sinon": "^1.17.4",
"sinon-chai": "^2.8.0"
```

**Comment by fatso83** [comment] 2016-07-09 06:13
@chrismllr: as you can see from the history, this will not receive any love until someone can contribute a code sample that is reproducible. A js bin is fine too. [tonicdev](https://tonicdev.com/npm/sinon) is even easier for sharing as you can require all you need. 

Do that and I can consider reopening this, or open a new issue.

**Comment by llchan** [comment] 2016-07-15 00:22
Seeing the same thing as @chrismllr, and confirming that it's fixed in 2.0.0-pre.  If you want to reproduce, it hits the error when `sinon.useFakeTimers()` is called, but since it's fixed in the upcoming 2.0.0 release it's probably not worth investigating.

**Comment by Vanuan** [comment] 2017-01-25 14:00
I think it happens somewhere here:

```
    if (isAMD) {
        define(loadDependencies);
    } else if (isNode) {
        loadDependencies(require, module.exports, module, require("lolex"));
    } else {
        makeApi(sinon); // eslint-disable-line no-undef
    }
```

When compiled with Webpack it goes to branch 3, hence it thinks that lolex is available in global scope. But it isn't. So both `lolex` and `lol` are undefined:

```
        var llx = typeof lolex !== "undefined" ? lolex : lol;
```

So to fix this it needs to detect whether it's using webpack and load lolex appropriately.

The relevelant webpack config part I'm using it the following:

```
  resolve: {
    alias: {
      // Conditional requires workaround
      // https://github.com/sinonjs/sinon/issues/830
      'sinon': 'sinon/pkg/sinon'
    },
  },
  module: {
    noParse: [
      // Conditional requires workaround
      // https://github.com/sinonjs/sinon/issues/830
      /node_modules\/sinon\//,
    ],
  },
```

**Comment by fatso83** [comment] 2017-01-25 14:02
@Vanuan, which version of Sinon are you using? Version 1 is explicitly non-compatible with bundlers like Webpack.

**Comment by Vanuan** [comment] 2017-01-25 14:07
```
    "sinon": "1.17.4",
```

**Comment by fatso83** [comment] 2017-01-25 14:21
@Vanuan, well there you go 🙂 Bundling is not supposed to work in 1.x versions. Try `sinon@next`. 

This bug is only relevant for non-bundles.

**Comment by Vanuan** [comment] 2017-01-25 14:46
Is there a migration guide? Or the api is the same?

**Comment by fatso83** [comment] 2017-01-26 12:41
There are some breaking changes, but mostly things will be the same:
[Migrating to 2.0](https://github.com/sinonjs/sinon/blob/master/docs/current/migrating-to-2.0.md)

**Comment by derekdon** [comment] 2017-02-24 15:32
@fatso83 When trying to use the sinon@next in webpack 2, I get errors related to colors.js

```
WARNING in ./~/sinon/~/colors/lib/extendStringPrototype.js
101:31-45 Critical dependency: the request of a dependency is an expression
```
It looks like a pull request was raised to move to chalk and it was merged into [master here](https://github.com/sinonjs/sinon/commit/912a097f4b860d8a239a1582471277896e457bcc)

Is this change due to go into 2?

**Comment by fatso83** [comment] 2017-02-24 15:58
@derekdon obviously, as it was integrated into `master` which is the basis for all non-1.x releases. Rumors have it that Sinon 2 might be a thing next week 🙂

**Comment by derekdon** [comment] 2017-02-24 16:17
@fatso83 sorry, not knowing the release schedule of 2, I meant into one of the pre release versions as it's not in https://github.com/sinonjs/sinon/blob/v2.0.0-pre.5/lib/sinon/spy.js. So wondering if v2.0.0-pre.6 was due to land, but it sounds like I won't need to wait long for 2 so that's cool. Thanks.

**Comment by derekdon** [comment] 2017-02-27 12:46
@fatso83 thanks for dropping v2.0.0-pre.6, my issues are resolved with it.
