### ISSUE TITLE
withArgs - error messages/proper usage ?

### ISSUE THREAD

**Issue by walshe** [sinonjs/sinon#1486] opened 2017-07-13 17:36 UTC
a bit of a newb to Sinon here really, but I notice that when I use withArgs and the obj is actually different to what gets actually passed , that the error message is really ugly and does not indicate differences of the arguments. 

```
serviceRequestUpsertStub.withArgs({
            uuid: messages[0].data.attributes.uuid,
            type: 'SMS',
            payload: JSON.stringify(messages[0].data.attributes.originalPayload),
            content: messages[0].data.attributes.content,
            timestamp: messages[0].data.attributes.timestamp
        }).returnsPromise().resolves({}, true);
```

or maybe I am using Sinon badly ? anyone got any advice ?

**Comment by fatso83** [comment] 2017-07-28 22:09
Thanks for your report. Unfortunately it's lacking on detail. You say the error is ugly, but fail to produce an actual error message or a reproducible snippet, which is specified in our issue template for us to be able to help you. This is probably also the reason no one has responded until now. I have actually no idea how those errors look from the top of my head 😕

The only thing I noticed is that I are using the API wrong. 

[From the docs](http://sinonjs.org/releases/v2.4.1/stubs/):
> stub.usingPromise(promiseLibrary);
>
> Causes the stub to return promises using a specific Promise library instead of the global one when using stub.rejects or stub.resolves. Returns the stub to allow chaining.

You only need to call this method of you intend on using a custom Promise implementation, instead of the native ones. 

Closing this issue as missing info, but feel free to reopen it if you find time to add some more detail!

**Closed** 2017-07-28 22:10 UTC

**Comment by walshe** [comment] 2017-07-31 14:57
heres the code under test:

```
models['ServiceRequest'].upsert({
                        vroomMessageUuid: message.data.attributes.uuid,
                        type: 'SMS',
                        payload: JSON.stringify(message.data.attributes.originalPayload),
                        content: message.data.attributes.content,
                        timestamp: message.data.attributes.timestamp
                    }).catch(function(error){
                        errorMessage = `smsJobQueueCronHandler - Error saving ${JSON.stringify(error)}`
                    }).finally(function(){
                        callback(errorMessage);
                    });
```


and here is the expectation in the unit test  (purposefully setting SMSX to force the error )

```
        serviceRequestUpsertStub.withArgs({
            vroomMessageUuid: messages[0].data.attributes.vroomMessageUuid,
            type: 'SMSX',
            payload: JSON.stringify(messages[0].data.attributes.originalPayload),
            content: messages[0].data.attributes.content,
            timestamp: messages[0].data.attributes.timestamp
        }).returnsPromise().resolves({catch: 'test'}, true);

```


1 failed

  endpoint test | GET /v1/smsJobQueueCronHandler | single message pulled from queue -> ServiceRequest saved, SMS sent, ProviderRequest saved, messages deleted from queue
  /Users/emmett/dev/xxx/email-integration/node_modules/async/dist/async.js:5273

  Error: Cannot read property 'catch' of undefined

  nextTask (node_modules/async/dist/async.js:5273:14)
  Object.waterfall (node_modules/async/dist/async.js:5283:5)
  processMessage (svc/v1/email-sms/handler/sms/smsJobQueueCronHandler.js:100:11)




is there some way I can get a better error message that makes the test fail with a better message e.g. indicating the difference in the expected json arg ?

**Comment by fatso83** [comment] 2017-08-01 07:24
As mentioned, you are using Sinon wrong: `returnsPromise().resolves({catch: 'test'}, true);`

This does not make any sense. Please [RTFM](http://sinonjs.org/releases/v2.4.1/stubs/). Remove `returnsPromise()` and fix your `resolves()` call. Maybe you intend to use `rejects()`. Hard to tell. 

Anyway: We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions. Posting it on [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tagging it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon) is another good option.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
