### ISSUE TITLE
Behavior of sandbox creation inconsistent with documentation.

### ISSUE THREAD

**Issue by divmain** [sinonjs/sinon#617] opened 2014-12-02 19:18 UTC
The provided [documentation](https://github.com/cjohansen/sinon-web/blob/master/docs/index.html#L1482-L1502) seems to indicate that a call to `sinon.sandbox.create` will create a sandbox with a default configuration (namely, enabled fake timers and fake server).

However, this is inconsistent with the actual behavior.  See [example fiddle](http://jsfiddle.net/8k0zv6tp/).  Instead, an unconfigured instance is returned with `sinon.sandbox` in the prototype chain ([link](https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/sandbox.js#L110-L112)).

It doesn't appear as if there is any default configuration behavior for sandboxes, so this section of the documentation is misleading at best.  Either the documentation or the behavior should be updated to be consistent with the other.  I'm happy to submit a PR for either of these cases, if you can point me in the preferred direction.

**Comment by tjunghans** [comment] 2016-01-19 12:59
I can confirm this with sinon@1.7.2. Not only is the documentation misleading as described by @divmain, but even if the default configuration as shown in the [sandbox documentation](http://sinonjs.org/docs/#sandbox) is used (see snippet below), only the `clock` property is available.

```js
sinon.defaultConfig = {
    // ...
    injectInto: null,
    properties: ["spy", "stub", "mock", "clock", "server", "requests"],
    useFakeTimers: true,
    useFakeServer: true
}
```

I'm also happy to help (/cc @mantoni)

**Comment by mroderick** [comment] 2017-05-28 07:49
The [current documentation shows how to create a sandbox without a config](https://github.com/sinonjs/sinon/blob/454e0fdb178dccb514f2ccf6b306fe6c44ec6b1d/docs/release-source/release/sandbox.md#var-sandbox--sinonsandboxcreate) and clearly states that `sinon.sandbox.create(config)` is an integration feature, that users are likely not to need.

I consider this solved, and am closing this. Feel free to create a PR for the new documentation if you have improvements for this area of the documentation.

**Closed by mroderick** 2017-05-28 07:49 UTC
Labels: Documentation

**Comment by ryan-roemer** [comment] 2017-05-28 12:20
I think perhaps a further exploration of the issue may help.

### Incorrect docs and/or behavior

The documentation says:

> #### `var sandbox = sinon.sandbox.create(config);`
> 
> The `sinon.sandbox.create(config)` method is mostly an integration feature, and as an end-user of Sinon.JS you will probably not need it.
> 
> Creates a pre-configured sandbox object. The configuration can instruct the sandbox to include fake timers, fake server, and how to interact with these.
> 
> The default configuration looks like:
> 
> ```javascript
> sinon.defaultConfig = {
>     // ...
>     injectInto: null,
>     properties: ["spy", "stub", "mock", "clock", "server", "requests"],
>     useFakeTimers: true,
>     useFakeServer: true
> }
> ```

This is, unfortunately, incorrect.

```js
sinon.sandbox.create({});
```

Does **not** get initialized like:

```javascript
{
    useFakeTimers: true,
    useFakeServer: true
}
```

but rather effectively:

```javascript
{
    useFakeTimers: false,
    useFakeServer: false
}
```

as @divmain 's fiddle (http://jsfiddle.net/8k0zv6tp/) shows.

If this is _intended_ behavior, you should update your documentation to indicate that 

> The default configuration looks like:
> 
> ```javascript
> sinon.defaultConfig = {
>     // ...
>     injectInto: null,
>     properties: ["spy", "stub", "mock", "clock", "server", "requests"],
>     useFakeTimers: true,
>     useFakeServer: true
> }
> ```

is incorrect, at least as far as `useFakeTimers` and `useFakeServer` (both are `false`). And I forget if `proprties` actually work correctly as documented or not.

Or, you could update your docs to suggest:

```js
sinon.sandbox.create(sinon.defaultConfig);
```

To actually get the defaults like the docs assume happens.

In any case I'm guessing @divmain is still happy to open a PR correcting the docs if the above is not considered a bug on your end.

So, hopefully you can reopen the ticket one way or another

### Sandbox as a first class citizen

Separately,

> is an integration feature, that users are likely not to need.

don't sell yourself short. We've been actively advocating the use of a global:

```js
beforeEach(() => {
  global.sandbox = sinon.sandbox.create({ foo });
});

afterEach(() => {
  global.sandbox.restore();
});
```

That all specs then leverage so that we guarantee to have *only one* sandbox that all tests use and mutate for specific faking uses. You'll be pleased to know that some very large companies with enormous test code bases rely on this basic construct as the foundation of their unit test fakes. The advantages are:

- Always restored
- No manual restores needed
- Can get uniform default behavior.

And having a lot of experience at this point with manual fake timer / server creation and management over huge test cases, if I were still writing [my book on JS testing](https://www.amazon.com/Backbone-js-Testing-Ryan-Roemer/dp/178216524X) I would actually say to "always use `sandbox`-es" over the raw fake timer / server / stub constructs.
