### ISSUE TITLE
QUnit 1.14 + Sinon 1.9 error: "require not defined"

### ISSUE THREAD

**Issue by artsyca** [sinonjs/sinon#471] opened 2014-04-23 11:57 UTC
Steps to reproduce:

  * QUnit 1.14 and Sinon 1.9 (within Teaspoon: https://github.com/modeset/teaspoon)
  * Sinon will attempt to `require` several modules starting around line 944
  * require is not defined

I am attempting to understand if this is a Teaspoon misconfiguration issue or a new requirement in Sinon or perhaps an issue with QUnit globals.

This was definitely working under 1.7.3 and I wonder if it's something along the same lines as #333?

**Comment by fatso83** [comment] 2016-07-11 09:33
Closing due to age and the fact that this should be fixed by now. It can be reopened if the issue is still there.

**Closed by fatso83** 2016-07-11 09:33 UTC
