### ISSUE TITLE
sinon.spy(object, "method") not working

### ISSUE THREAD

**Issue by manodupont** [sinonjs/sinon#1011] opened 2016-03-18 21:42 UTC
i have this 
```javascript
var postToChannel = sinon.spy(avidBus, "postToChannel");

avisBus.postToChannel();

sinon.assert.calledOnce(postToChannel);
```

This is always false.!!! Why

**Comment by fatso83** [comment] 2016-03-19 12:05
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions. [StackOverflow](http://stackoverflow.com) might also be a source of help (tag with `sinon`).

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by fatso83** [comment] 2016-03-19 12:12
Forgot my previous comment (deleted,btw). Could you please post a reproducible test case (js bin for instance), and please follow [our guidelines for contributing](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue). Otherwise this will receive no love.

**Comment by fatso83** [comment] 2016-03-19 22:03
You will often find that when trying to simply your code to an example that is suitable as a reproducible test case that we can use, you find the error. The code you posted looks fine and should work, so I'd rather have a closer look at your own code (could it call itself to make `callCount` > 1?). Closing this until you can provide us with a test case demonstrating a bug.

**Closed by fatso83** 2016-03-19 22:03 UTC
