### ISSUE TITLE
publish to npm / versioning inconsistency

### ISSUE THREAD

**Issue by necolas** [sinonjs/sinon#896] opened 2015-10-24 20:21 UTC
npm: 1.17.2
package.json: 1.17.0

It looks like 1.17.2 was published from not-master, and still errors with webpack. While master fixes the webpack issues that there have been so many issues about. Please can we get a working version from master published to npm ASAP?

--
edit (@fatso83): updated version numbers

**Comment by fatso83** [comment] 2015-10-26 12:07
This issue does show some issues with the current `release.sh` script as it does not ensure that the following holds at publish time:

1. The version field in `package.json` is X.Y.Z
2. The published version on NPM will by X.Y.Z
3. A release has been tagged with X.Y.Z

I think we should consider integrating `npm version major | minor | patch` into the build process somehow to tackle this. 

Ideas, problems, @mroderick , @mantoni ?

**Comment by mroderick** [comment] 2015-10-26 19:38
> npm: 1.17.2
> package.json: 1.17.0
> 
> It looks like 1.17.2 was published from not-master, and still errors with webpack. While master fixes the webpack issues that there have been so many issues about. Please can we get a working version from master published to npm ASAP?

Are you using Sinon.JS from `master`?

`1.17.2` was published from the `1.17` branch.

I would like to merge https://github.com/sinonjs/sinon/pull/891 before cutting the `2.0.0` release. Once that is in, I think we can publish from master again.

**Comment by mroderick** [comment] 2015-10-26 19:44
@fatso83 I don't think we can make the release process atomic across filesystem, git tags and npm repository. But, there are certainly things we can do.

We could improve `release.sh` to do something like this

1. Fail if not called with a valid semver as argument
2. Build the dist version
3. Write semver to package.json + git tag (use npm version).
4. Commit the changes
5. Publish a git tag 
6. Publish npm version

It's only the last two steps that are "dangerous", as they require a lot of work to back out of.

**Comment by necolas** [comment] 2015-10-26 20:24
hi. My first interest is in being able to install a version of sinon from npm that webpack can bundle. Master seems to work, but what is on npm does not. I cannot depend on a git-install for the app we're working on. Then it was confusing to find that a git-install from master logged `1.7.0`, while an older release on npm is at `1.7.2`. Thanks

**Comment by fatso83** [comment] 2015-10-27 09:42
Really hope you mean 1.17.0 and 1.17.2 (as I edited in your original
issue), because those version numbers you gave are years old.

**Comment by necolas** [comment] 2015-10-27 18:12
yeah. i seem to be intent on getting it wrong every time :)

**Comment by necolas** [comment] 2016-02-02 19:27
Hi, is there any progress on this or when we could expect a build that works with webpack?

**Comment by fatso83** [comment] 2016-02-10 07:42
If you could spare some time on the various sub tasks related to [preparing for the 2.0 release](https://github.com/sinonjs/sinon/issues/966) you can get your build sooner :-) It's currently at a bit of a stand still.

**Comment by fatso83** [comment] 2016-02-10 08:00
Duplicate of #830

**Closed by fatso83** 2016-02-10 08:00 UTC

**Comment by fatso83** [comment] 2016-02-10 09:02
PS. We did a pre-release of 2.0 which you can get by doing `npm install sinon@next`
