### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by praveenkumarct** [sinonjs/sinon#2427] opened 2022-01-27 06:13 UTC
**Describe the bug**
With the latest version 12 and above, We have an issue working with eslint and sinon.

```
> eslint lib test-unit test-integration

TypeError: Cannot read property 'split' of undefined
Occurred while linting /Users/praveenkumar/osWorskpace/zeg-cli/test-unit/mock-base-service.js:3
    at checkDependencyDeclaration (/Users/praveenkumar/osWorskpace/zeg-cli/node_modules/eslint-plugin-import/lib/rules/no-extraneous-dependencies.js:133:40)
    at reportIfMissing (/Users/praveenkumar/osWorskpace/zeg-cli/node_modules/eslint-plugin-import/lib/rules/no-extraneous-dependencies.js:187:38)
    at commonjs (/Users/praveenkumar/osWorskpace/zeg-cli/node_modules/eslint-plugin-import/lib/rules/no-extraneous-dependencies.js:264:7)
    at checkSourceValue (/Users/praveenkumar/osWorskpace/zeg-cli/node_modules/eslint-module-utils/moduleVisitor.js:29:5)
    at checkCommon (/Users/praveenkumar/osWorskpace/zeg-cli/node_modules/eslint-module-utils/moduleVisitor.js:67:5)
    at visitors.CallExpression (/Users/praveenkumar/osWorskpace/zeg-cli/node_modules/eslint-module-utils/moduleVisitor.js:105:29)
    at /Users/praveenkumar/osWorskpace/zeg-cli/node_modules/eslint/lib/util/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/praveenkumar/osWorskpace/zeg-cli/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/praveenkumar/osWorskpace/zeg-cli/node_modules/eslint/lib/util/node-event-generator.js:251:26)
```

**To Reproduce**

1. In any nodejs application, add the below libraries to package.json:
     `eslint - 5.16.0` and `sinon - 12.0.0`
2. Try running `node_modules/.bin/eslint lib test-unit test-integration` (any one folder 'lib' or 'test-unit' or 'test-integration').
3. `eslint` will return an error as shown above. (When I use Sinon library older version (Ex: 11.1.2) we don't have any issues).

**Expected behavior**
Expecting `sinon` latest versions to be compatible with the latest `eslint-5.16.0` and latest versions.

- Library version used:
 node - 14.18.1
 eslint - 5.16.0
 sinon - 12 and above. (also with the latest 12.0.1)

**Comment by fatso83** [comment] 2022-01-27 09:45
Hi, thanks for filing this issue. Unfortunately, I will probably need to close this as it is very unclear how I would I reproduce this. This is obviously not an issue for most people and we already run ESLint on our own codebase.

Could you please follow the issue template and provide a minimal reproducible example?

**Comment by praveenkumarct** [comment] 2022-01-27 09:48
Thank you @fatso83 for the quick response. I will update the description to make it more clear to reproduce the issue.

**Comment by fatso83** [comment] 2022-02-03 10:00
No update. Closing as unable to reproduce.

**Closed by fatso83** 2022-02-03 10:00 UTC

**Comment by praveenkumarct** [comment] 2022-03-01 08:36
Hello @fatso83, I have updated the steps to reproduce the issue. Could you please check now?

**Comment by mroderick** [comment] 2022-03-08 14:28
@praveenkumarct I tried creating a repository using the instructions above, and am not seeing the error you describe.

https://github.com/mroderick/sinon-2427

Would it be possible for you to create a runnable example that can be shared, so that we may be able to see the error that you're seeing?

**Comment by praveenkumarct** [comment] 2022-03-15 08:49
Thank you so much @mroderick for doing this. I would come back with running example soon.
