### ISSUE TITLE
Timeout error occurs changing patch version from 1.17.3 to 1.17.4

### ISSUE THREAD

**Issue by jeffgaynor** [sinonjs/sinon#1055] opened 2016-05-27 15:56 UTC
When running Mocha / Chai / Sinon tests, timeouts now occur when changing patch version of sinon from 1.17.3 to 1.17.4.

* Sinon version : 1.17.4
* Environment   :  local development, Mac OS X 10.11.4, npm version 3.3.12
* Example URL  : 
* Other libraries you are using:

├── chai@3.5.0
├── jscs@3.0.3
├── jshint@2.9.2
├── JSON2@0.1.0
├── mochify@2.18.0
├── phantomjs-prebuilt@2.1.7
└── sinon@1.17.4

**What did you expect to happen?**

Tests pass ok. 

**What actually happens**

Changing version from sinon@1.17.3 to 1.17.4 causes timeout errors to occur.

Some debug output:
```
jshint . && jscs . && mochify
# phantomjs:

  86 passing (36s)
  18 failing

  1) #auth() response should return error when we get a 400 response:
     timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.


  2) #auth() response should return error when we get a 401 response:
     timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**How to reproduce**

Run test code like:
```
      it('should return error when we get a 400 response', function (done) {

            api.auth('test@example.com', null, function (err) {

                expect(err).to.be.ok;
                done();

            });

            request.respond(400, {}, '{}');

        });

        it('should return error when we get a 401 response', function (done) {

            api.auth('test@example.com', null, function (err) {

                expect(err).to.be.ok;
                done();

            });

            request.respond(401, {}, '{}');

        });
```

**Comment by fatso83** [comment] 2016-05-27 17:28
Thanks for reporting. Which browser is this?

**Comment by jeffgaynor** [comment] 2016-05-27 17:32
We're running it headless, via PhantomJS.

**Comment by jmtoball** [comment] 2016-05-30 15:19
Similar issue here. We're also running our tests via PhantomJS. When I add logging, it seems to me that the fakeServer-responses are now sent deferred after the actual test code has run. Reverting to 1.7.3 makes it work.

**Comment by fatso83** [comment] 2016-05-31 08:58
I have an easy recipe with an [accompanying script](https://raw.githubusercontent.com/fatso83/Sinon.JS/setImmediate-bug/test-script.sh) for finding the offending change [here](https://github.com/sinonjs/sinon/issues/821#issuecomment-139280107). If someone has some time they could easily modify it to find where this change was introduced.

**Comment by jmtoball** [comment] 2016-05-31 09:20
Will do

**Comment by jmtoball** [comment] 2016-05-31 09:48
first bad commit: [2cfbacd5cea5b63c014076d3a65b6642b2200793] Re-did #861 for v1.17 branch

**Comment by fatso83** [comment] 2016-05-31 09:54
@fearphage seems like #1017 (i.e. #861) ended up causing some problems.

**Comment by fearphage** [comment] 2016-06-01 17:59
This looks like a dupe of #1040.

**Comment by fatso83** [comment] 2016-06-01 18:10
Closing as dupe of #1040 . Follow discussions there.

**Closed by fatso83** 2016-06-01 18:10 UTC
