### ISSUE TITLE
Spies stop functioning after ES6 `await` statement

### ISSUE THREAD

**Issue by elliotykim** [sinonjs/sinon#1735] opened 2018-03-14 21:29 UTC
* Sinon version: 4.4.5
* Environment: node@9.2.0
* Example URL: 
* Other libraries you are using: mocha@5.0.4, chai@4.1.2, babel-core@6.26.0, babel-preset-es2015@6.24.1

**What did you expect to happen?**
I expect spies, stubs and mocks to continue functioning after `await` is called in an `async` function.

**What actually happens**
All of the spies in the function under test work as expected prior to a line with `await`, but immediately afterwards, they stop functioning. `callCount` stops incrementing and `getCall` doesn't return all calls.

**How to reproduce**
After running, mock.spy1.callCount will be 1 and mock.spy2.callCount will be 0

```js
async function testAwait() {
  spy1()
  await anotherFunction()
  spy2()
}
```

My test command: `mocha --require babel-core/register './**/*.tests.js'`

**Comment by mroderick** [comment] 2018-03-15 07:26
Your example is not exactly runnable: the spies are never declared, neither is `anotherFunction`.

I created my own example to see if I could reproduce the behaviour you're seeing

```js
const sinon = require('sinon');
const spy1 = sinon.spy();
const spy2 = sinon.spy();

async function anotherFunction(){
    return true;
}

async function testAwait() {
    spy1()
    await anotherFunction()
    spy2()
}

testAwait();
console.log(spy1.callCount);
console.log(spy2.callCount);    
```

If I run that in node@8, which has `async/await`, then the output is

```text
1
0
```

That is because we're not waiting for the promise returned by `testAwait` before trying to access the values of the spies, and spy2 won't have been called yet.

If we do wait for the promise to resolve, then things are different

```js
testAwait().then(function (){
    console.log(spy1.callCount);
    console.log(spy2.callCount);    
});
```

Outputs

```
1
1
```

To me this shows that Sinon behaves as expected, so I am closing this.
If you're able to reproduce the error and can create a complete, runnable test case, please re-open the issue and add the test case.

**Closed by mroderick** 2018-03-15 07:26 UTC

**Comment by elliotykim** [comment] 2018-03-15 17:41
Thanks for your thorough investigation, @mroderick. You're right, there's nothing wrong with sinon.

I forgot to call `await` in my test case. Much appreciated!

**Comment by sharjeelahmed99** [comment] 2021-03-01 11:09
Facing the same issue, calling testAwait() with await keyword but in my case, I'm calling forEach async function inside testAwait.
Would you try this 

const sinon = require('sinon');
const spy1 = sinon.spy();
const spy2 = sinon.spy();

async function anotherFunction(){
    return true;
}

async function testAwait() {
[1,2].forEach(async (no) => {
    spy1()
    await anotherFunction()
    spy2()
}
});
await testAwait();
console.log(spy1.callCount);
console.log(spy2.callCount);
