### ISSUE TITLE
My webpage slows down gradually using sinon.js

### ISSUE THREAD

**Issue by lexterror** [sinonjs/sinon#2212] opened 2020-02-03 00:07 UTC
Hi, I wanted to know whether I can do anything about sinon.js slowing down my webpage gradually.

Thank you!

**Comment by fatso83** [comment] 2020-02-03 10:19
**This issue is lacking relevant information, preventing it from being worked on**. We have no idea
- how to reproduce this
- where it happens
- which environment this happens in
- the url of your webpage
- why on earth you would include Sinon, a library for unit testing, in a production site

For us to work on this you need to do some work as well 😄 

---

The reason we have an [issue template](https://github.com/sinonjs/sinon/blob/master/.github/ISSUE_TEMPLATE.md) is for issues to have sufficient detail  to be able to be worked on.

This issue lacks some or all of the information needed for us to do something meaningful about it.

We usually ask for this to be provided:

* Sinon version :
* Environment   :
* Example URL   :
* Other libraries you are using:

**What did you expect to happen?**

**What actually happens**

**How to reproduce**
> Describe in sufficient detail how to reproduce the faulty behaviour for the person that should choose to work on the problem

<details>
    <summary>Really long code sample or stacktrace</summary>

    If you need to provide a dump of a stack trace or
    other lengthy material, such as 80 lines of example code,
    please stuff it in a `<details>` tag such as this
    to make the issue more readable. Thanks.
</details>

**Comment by mroderick** [comment] 2020-02-03 11:22
This is a duplicate of https://github.com/sinonjs/sinon/issues/2211

**Closed by mroderick** 2020-02-03 11:22 UTC
Labels: Awaiting Response, Unverified
