### ISSUE TITLE
.calledWith() on a stub broke in sinon 4.4.10

### ISSUE THREAD

**Issue by tomi** [sinonjs/sinon#1756] opened 2018-03-28 10:34 UTC
* Sinon version : 4.4.10
* Environment   : Chrome 62
* Example URL   : -
* Other libraries you are using: mocha, testem

**What did you expect to happen?**
Tests to work as before

**What actually happens**
Tests break with '.calledWith is not a function' exception.

**How to reproduce**
1) Create a stub
```js
const stub = sinon
  .stub()
  .onCall(0)
  .resolves(createResponse)
  .onCall(1)
  .resolves(validateResponse)
  .onCall(2)
  .resolves(downloadResponse)
```
2) Call `calledWith` on that stub
```js
const stub.calledWith(...)
```

Downgrading to 4.4.9 solves the issue.

**Comment by fatso83** [comment] 2018-03-28 11:30
@nfriedly, this is most probably related to merging #1738. Could you shine some light on this?

**Comment by nfriedly** [comment] 2018-03-28 11:34
Yea, I think this variation will work as desired:

```js
const stub = sinon .stub();

stub.onCall(0)
 .resolves(createResponse) 
 .onCall(1) .resolves(validateResponse)
 .onCall(2) .resolves(downloadResponse);
```

**Comment by fatso83** [comment] 2018-03-28 11:50
After first thinking this is real regression (I marked 4.4.10 transiently as `deprecated`), I now think this actually just shines some light on an undocumented "feature"/behaviour, as I recognize the current behaviour as how things have used to work in the past.

I think this might as well be addressed by adding an explicit test in our test arsenal that asserts that the behaviour adding methods (such as `onCall`, `resolves`, etc) does _not return the stub_. I think the provided example from @nfriedly is a reasonable cost for those being affected by this.

What do you think, @mroderick?

**Comment by fatso83** [comment] 2018-03-28 12:08
Closing this as a non-bug, as our official stance has been that using inlined stubs is not supported: https://github.com/sinonjs/sinon/issues/1748#issuecomment-376861414

I'll try to open a new feature request issue to see if we can improve the situation.

**Closed by fatso83** 2018-03-28 12:08 UTC

**Comment by mroderick** [comment] 2018-03-28 18:47
> I think this might as well be addressed by adding an explicit test in our test arsenal that asserts that the behaviour adding methods (such as onCall, resolves, etc) does not return the stub. I think the provided example from @nfriedly is a reasonable cost for those being affected by this.
> 
> What do you think, @mroderick?

I think that would be a great idea, as it makes it clear what the intention is, without having to resort to using `git bisect` to figure it out.

**Comment by fatso83** [comment] 2018-03-29 08:17
I have done a lot `git bisecti`ing on this now, and it seems _I_ actually merged explicit support for chaining behaviour methods in @zuzusik's #1227 PR, meaning it was (a badly documented) part of the API. 

A problem is that the feature description was not fully covered by the tests in that same PR. The tests explicitly just tested that `onCall().returns()` chaining worked, not the general behaviour concept. Another problem is of course that I didn't understand all the implications this would have, as our tests are very focused and avoid the intricacies of long method chains (where the problems of fluent API really comes to the surface). :nauseated_face: 

Since we explicitly merged this feature, which should perhaps be called "support for inline creation of stub with behaviours", it means it's part of the official API, which 4.4.10 is breaking. As a temporary solution I have deprecated 4.4.10, but we will need to discuss the next step.

**Comment by mroderick** [comment] 2018-03-30 12:44
Please continue this discussion in #1757
