### ISSUE TITLE
New stub API failing after replacing calls with .callsFake

### ISSUE THREAD

**Issue by nfantone** [sinonjs/sinon#1341] opened 2017-03-19 22:18 UTC
* Sinon version : `2.0.0`
* Environment   : node `7.7.3`
* Other libraries you are using: `sinon-test`, `sinon-chai`, `chai`.

**What did you expect to happen?**
Migrating `sinon.stub` syntax from `1.x` to `2.0.0` either manually or using  [`sinon-codemod`](https://github.com/hurrymaplelad/sinon-codemod) should not alter test output.

**What actually happens**
All tests using a stubbed object fail with an endless stacktrace (excerpt shown below).

```sh
 at Object.proxy [as prefetch] (node_modules/sinon/lib/sinon/spy.js:97:22)
      at Object.invoke (node_modules/sinon/lib/sinon/behavior.js:130:32)
      at Object.functionStub (node_modules/sinon/lib/sinon/stub.js:83:53)
      at Function.invoke (node_modules/sinon/lib/sinon/spy.js:190:51)
      at Object.proxy [as prefetch] (node_modules/sinon/lib/sinon/spy.js:97:22)
      at Object.invoke (node_modules/sinon/lib/sinon/behavior.js:130:32)
      at Object.functionStub (node_modules/sinon/lib/sinon/stub.js:83:53)
      at Function.invoke (node_modules/sinon/lib/sinon/spy.js:190:51)
      at Object.proxy [as prefetch] (node_modules/sinon/lib/sinon/spy.js:97:22)
      at Object.invoke (node_modules/sinon/lib/sinon/behavior.js:130:32)
      // ....
```

Reverting _back to the old syntax_ prints out a warning, but makes all tests work as expected:

```sh
sinon.stub(obj, 'meth', fn) is deprecated and will be removed fromthe public API in a future version of sinon.
 Use stub(obj, 'meth').callsFake(fn).
 Codemod available at https://github.com/hurrymaplelad/sinon-codemod
```

> On a related note, there's a typo in the warning message: `"fromthe public"` -> `"from the public"`

Also, calls like these will show the exact same warning - although I'm not really sure what's the new expected syntax there:

```js
this.stub(seneca, 'export')
        .withArgs('transport/utils').returns(transportUtils);
```

**How to reproduce**
In my scenario, it was as simple as replacing calls like this:

```js
sinon.stub(channel, 'assertQueue', channel.assertQueue);
```

With the new `2.0.0` stub API:

```js
sinon.stub(channel, 'assertQueue').callsFake(channel.assertQueue);
```

You can also try and pull the entire failing test suite from `seneca-amqp-transport` repo:

```sh
git clone -b enhancement/sinon-2.0.0 --single-branch git@github.com:senecajs/seneca-amqp-transport.git
cd seneca-amqp-transport && npm i
npm run validate
```

**Comment by fatso83** [comment] 2017-03-20 06:03
Thanks for providing a good issue and test case! I will look into it, and it seems we might also need to update/add to the docs on this matter.

**Comment by nfantone** [comment] 2017-03-20 15:25
@fatso83 You're welcome. Let me know it need something else.

**Comment by nfantone** [comment] 2017-03-20 18:33
@fatso83 Just tried with newly released `2.1.0` and the same thing happens, unfortunately. No idea if this was actually tackled (probably not, seen as this issue is still open), but just thought you'd like to know.

**Comment by nfantone** [comment] 2017-03-20 18:35
One thing that _could_ be problematic is the usage of `sinon-chai` which has an explicit peerDependency on `sinon < 2`. Doesn't explain why using the old syntax would actually work, though.

**Comment by lucasfcosta** [comment] 2017-03-30 20:32
Hi @nfantone, since I know the Chai codebase and a bit about a few of its plugins I'll take a look at how sinon-chai works and I'll let you know my findings.

If you have any other ideas or code examples please let me know.

**Comment by nfantone** [comment] 2017-03-30 20:58
How would I go about turning my stubs into spies? Would spies call a fake method as well? Could you give me an example? Say we have something like my original example:

```js
sinon.stub(channel, 'assertQueue', channel.assertQueue);
```

What should the new syntax look like using spies?

**Comment by lucasfcosta** [comment] 2017-03-30 21:46
By doing this you are just telling your stub to call the original `channel.assertQueue` method, which is exactly the same as just using a spy, which allows you to keep track of calls, arguments and other important pieces of information while still calling the old behavior.

You could, for example, turn this:

```js
sinon.stub(channel, 'assertQueue', channel.assertQueue);
```

Into this:

```js
sinon.spy(channel, 'assertQueue');
```

If you just want to keep track of calls and other information use a [`spies`](http://sinonjs.org/releases/v2.1.0/spies), if you need to change behavior use a [`stubs`](http://sinonjs.org/releases/v2.1.0/stubs/).

**Comment by nfantone** [comment] 2017-03-31 12:17
@lucasfcosta Well, it turns out you were right. I wasn't aware that `.spy` would actually _call_ the original method you are spying on. I replaced most `.stub` calls with `.spy` and now all tests are passing.

I still have that little issue about the syntax update warning on things like:

```js
  this.stub(seneca, 'export').withArgs('transport/utils').returns(transportUtils);
```

How should that be updated?

**Comment by emirotin** [comment] 2017-04-24 18:51
I actually need the `callsFake` behavior and it seems to fail for me, too. I mean the stubbed function is simply returning `undefined`. I've tried debugging it and it looks like the `fake` is recorded but `this.fakes` is still empty in the spy.

Going back to the original 3-args syntax works.

**Comment by lucasfcosta** [comment] 2017-04-24 19:47
Hi @emirotin, can you please provide a reproducible example? I had a hard time reproducing this in a concise example, which makes things a lot easier for me to detect and fix possible bugs.

@nfantone Sorry for the delay on answering you, I've been very busy in the last days.
I tried to reproduce the warnings you mentioned by using the following test code and I couldn't get any warnings, both using the master branch and the tagged `v2.0.0` commit:

```js
var stub = sinon.stub;
var obj = {
  bla: function () { return 'foo' }
}
                                                 
stub(obj, 'bla').withArgs('lol').returns('bar');
                                                 
assert(obj.bla('lol'), 'bar')
```

Can you provide a small reproducible example so I can dig into this more deeply?

**Comment by emirotin** [comment] 2017-04-24 20:09
Huh I can't reproduce in the simplistic cases. That's really strange as I have a project where it's reproducible.  Let me create a reduced version of it

**Comment by emirotin** [comment] 2017-04-24 20:20
Ah, here it is!

Looks like `reset` is erasing the fake:

```
var sinon = require('sinon')

var x = {
    a: function() {
        return 'Fail'
    }
}

var sandbox = sinon.sandbox.create();

sandbox.stub(x, 'a').callsFake(function() {
    return 'OK'
})

console.log(x.a())

sandbox.reset();

console.log(x.a()) // <-- undefined
```

**Comment by lucasfcosta** [comment] 2017-04-24 21:45
Thanks @emirotin!

So, according to the docs I believe this is correct behavior, right?

Let's wait for @nfantone's answer so we can fix and hopefully close this.

**Comment by emirotin** [comment] 2017-04-25 06:55
I'm not sure it's correct even according to the docs. And definitely works against my intuition.
I reset to reset the _state_ of fakes, but not remove the fakes from the stub.
Like it's expected to reset the call counts, last args, last result, things like that.

My expectations from `callsFake` is that it's part of the setup and shouldn't be gone after reset which I read as "make everything look as right after the original setup".

And definitely it's different from the previous 3-arg form but it's advertised by the warning as the new equivalent to it.
But the old API is immune to resets.

**Comment by lucasfcosta** [comment] 2017-04-25 19:14
@emirotin I agree with you regarding the name consistency.

I've commented the same thing at #1371. I think we must have consistent names for the reset API.

I'll be more than happy to make a PR for that if the project's maintainers agree with this change.

Let's wait to hear the maintainers' thoughts.

**Comment by nfantone** [comment] 2017-04-26 18:12
@lucasfcosta Sorry for the delay here.

> Can you provide a small reproducible example so I can dig into this more deeply?

The test suite included in (seneca-amqp-transport)[https://github.com/senecajs/seneca-amqp-transport] reproduces the issue and outputs the warning.

Just clone the repo, install deps, run `npm test`. You should see something like:

```sh
    the handleMessage() function
      ✓ should handle the request when a message is consumed
sinon.stub(obj, 'meth', fn) is deprecated and will be removed from the public API in a future version of sinon.
 Use stub(obj, 'meth').callsFake(fn).
 Codemod available at https://github.com/hurrymaplelad/sinon-codemod
```
I know it may not be a _small_ example, but it sure is real **and** reproducible.

On a side note, I agree with @emirotin sentiment on the `.reset` and `.callsFake` behaviour. If the new API is meant to be a "compatible replacement", that is.

**Comment by deyhle** [comment] 2017-06-29 08:04
Took me quite some time to figure out, because for me the simple replacement with `.callsFake` wasn't working, too. When replacing all `reset()` calls with `resetHistory()`, as @emirotin discovered, it actually works again. This should really be part of the deprecation/update guide.

**Comment by mqliutie** [comment] 2018-05-03 07:29
`Promise.then` not work in `callsFake` method?
```
// first way
store.dispatch(deleteById(id)).then(()=>{
     // can arrived here
 })
// second way
sinon.stub(wrapper.find(Account).instance(), "_deleteById").callsFake((id)=>{
     // truly http request by axios
     store.dispatch(deleteById(id)).then(()=>{
          // can't arrived here
      })
});
```
in aciton 
```
export function deleteById(id){
    return dispatch=>{
        return axios.put(url,data).then(()=>{
              // can't arrived here second way but first arrived
        })
    }
}
```

**Comment by MichaelHindley** [comment] 2018-05-14 08:57
@mqliutie it would appear so, at least in latest Chrome on MacOS, bumped into this in Cypress Graphql Stubbing (https://github.com/cypress-io/cypress-documentation/issues/122)

**Comment by mqliutie** [comment] 2018-05-14 09:36
@MichaelHindley  Call `done()`  will work. I don't know is this right way

**Comment by fatso83** [comment] 2018-05-14 21:40
I think I reopened this accidentally. Closing, as the [docs explicitly mention this](http://sinonjs.org/guides/migrating-to-2.0#stubresethistory-replaces-stubreset).

**Closed by fatso83** 2018-05-14 21:40 UTC
