### ISSUE TITLE
`sinon.test` restores stubs before async tests are completed

### ISSUE THREAD

**Issue by nufercle** [sinonjs/sinon#1122] opened 2016-08-08 15:13 UTC
* Sinon version : 1.17.5
* Environment   :
  - Safari 9.1.1 (Mac OS X 10.11.5)
  - Firefox 48.0.0 (Mac OS X 10.11.0)
  - Chrome 52.0.2743 (Mac OS X 10.11.5)
* Example URL   :
* Other libraries you are using: 
  - Mocha
  - Chai
  - Karma
  - babel-plugin-transform-async-to-generator

**What did you expect to happen?**
`sinon.test` should restore stubs after test completion

**What actually happens**
`sinon.test` restores stubs before test completion

**How to reproduce**
```javascript
const toStub = {
  foo: async function () { return 'foo' },
  bar: async function () { return 'bar' }
}

const sut = async function () {
  const foo = await toStub.foo()
  const bar = await toStub.bar()
  
  return { foo, bar }
}

describe.only('test cases', () => {
  describe('a basic async test', () => {
    it('passes', async () => {
      const { foo, bar } = await sut()
      
      assert.equal(foo, 'foo')
      assert.equal(bar, 'bar')
    })  
  })
  
  describe('async test wrapped in `sinon.test`', () => {
    it('fails', sinon.test(async function () { 
      const fooStub = this.stub(toStub, 'foo', async function () { return 'first'})
      const barStub = this.stub(toStub, 'bar', async function () { return 'second'})
      
      const { foo, bar } = await sut()
      
      assert.equal(foo, 'first')
      assert.equal(bar, 'second')
      //expected 'bar' to equal 'second'
    }))
  })

  describe('async test using manual restore', () => {
    it('passes', async function () { 
      const fooStub = sinon.stub(toStub, 'foo', async function () { return 'first'})
      const barStub = sinon.stub(toStub, 'bar', async function () { return 'second'})
      
      const { foo, bar } = await sut()
      
      assert.equal(foo, 'first')
      fooStub.restore()
      assert.equal(bar, 'second')
      barStub.restore()
    })
  })
})
```

<details>
    <summary>assertion error stacktrace</summary>

    AssertionError@/Users/**/code/**/node_modules/chai/chai.js:5553:27
      assert@/Users/**/code/**/node_modules/chai/chai.js:206:31
      equal@/Users/**/code/**/node_modules/chai/chai.js:2277:16
      _callee7$@/Users/**/code/**/test/tests_index.js:35338:28 <- webpack:///Users/**/code/**/test/async-stub-test.js:31:19
      tryCatch@/Users/**/code/**/test/tests_index.js:7364:45 <- webpack:///Users/**/code/**/~/babel-polyfill/~/regenerator-runtime/runtime.js:62:14
      invoke@/Users/**/code/**/test/tests_index.js:7638:31 <- webpack:///Users/**/code/**/~/babel-polyfill/~/regenerator-runtime/runtime.js:336:0
      /Users/**/code/**/test/tests_index.js:7397:29 <- webpack:///Users/**/code/**/~/babel-polyfill/~/regenerator-runtime/runtime.js:95:0
      step@/Users/**/code/**/test/tests_index.js:35181:192 <- null:0:0
      /Users/**/code/**/test/tests_index.js:35181:373 <- null:0:0
      run@/Users/**/code/**/test/tests_index.js:4156:30 <- webpack:///Users/**/code/**/~/babel-polyfill/~/core-js/modules/es6.promise.js:89:0
      /Users/**/code/**/test/tests_index.js:4169:32 <- webpack:///Users/**/code/**/~/babel-polyfill/~/core-js/modules/es6.promise.js:102:0
      flush@/Users/**/code/**/test/tests_index.js:4514:12 <- webpack:///Users/**/code/**/~/babel-polyfill/~/core-js/modules/_microtask.js:18:0
</details>

**Comment by fatso83** [comment] 2016-08-08 15:39
@nufercle : this is a great issue report. Thank you! Still, I am closing it, but only because it seems to be a duplicate of #1119 (reported a few hours ago). Try following that if you can, maybe collaborating with @joelmukuthu on a fix?

**Closed by fatso83** 2016-08-08 15:39 UTC

**Comment by fatso83** [comment] 2016-08-08 15:46
@nufercle : I am not totally in on all the new generator and async stuff in ES2015 and how that translates to vanilla ES5, but I was under the impression that `await` basically returns a `Promise`, n'est-ce pas?

Just checking to see that I did not close this prematurely. It might be worth translating the gist of it into ES5, if you think there is something I missed in the issue report
