### ISSUE TITLE
Unable to install sinon

### ISSUE THREAD

**Issue by arankhem** [sinonjs/sinon#1894] opened 2018-09-06 08:22 UTC
**Describe the bug**
Unable to install sinon.js from few days.

**To Reproduce**
run the following command
npm i sinon

Error:

npm i sinon
npm ERR! code ETARGET
npm ERR! notarget No matching version found for just-extend@^3.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'nise'
npm ERR! notarget
**Expected behavior**
sinon latest version should be installed.

**Screenshots**

**Context (please complete the following information):**
Tried by installing other versions of sinon for example
npm i sinon@6.0.0

**Comment by mroderick** [comment] 2018-09-06 08:27
Please don’t tag maintainers in issues, we get plenty of e-mail already.

The issue you’re experiencing is most likely in your local system. Try clearing your npm cache and make sure your npm is a recent version. Older versions do not understand scopes

**Comment by arankhem** [comment] 2018-09-06 08:56
Cleared npm cache using `npm cache clean --force`
verified npm cache using `npm cache verify`

Npm version on my machine is 6.4.1 (latest)

My local machine is window

Facing the same issue in other local machines as well

**Comment by promosjotte** [comment] 2018-09-06 11:37
getting this:
```
npm install --save-dev sinon
npm ERR! Unexpected end of JSON input while parsing near '..."mochify":"^5.6.1","m'
```

**Comment by arankhem** [comment] 2018-09-06 12:32
I am bit confused here

Latest version of just-extend is 1.1.27. see [here](https://npmjs.itcs.hpecorp.net/package/just-extend)
![image](https://user-images.githubusercontent.com/32890972/45156679-7fdf0f80-b1fc-11e8-9e85-0a842ff84cd3.png)

Below is the screenshot from semver version calculator
![image](https://user-images.githubusercontent.com/32890972/45157511-01d03800-b1ff-11e8-8716-cc4f757e702a.png)


And [here](https://github.com/sinonjs/nise/blob/master/package.json#L59) in nice we are using just-extend^3.0.0 in package.json

And when i am doing `npm install just-extend@latest` it is installing 
+ just-extend@1.1.27
updated 1 package in 17.501s

Ans when i am doing `npm install nise@latest` am getting below error (latest version is 1.4.4)

npm install nise@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for just-extend@^3.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'nise

And when i am doing `npm install nise@1.4.3` it is getting installed
+ nise@1.4.3
added 7 packages from 14 contributors in 30.33s

**Comment by fatso83** [comment] 2018-09-06 20:02
@arankhem The site you linked to, https://npmjs.itcs.hpecorp.net/package/just-extend, is not an official site. Use npmjs.com to see version 3, released [3 weeks ago](https://www.npmjs.com/package/just-extend). Also, the semver calculator is clearly showing it to the left. 

If your NPM has problems finding it, I suspect your local settings is at fault. Maybe you or your local administrator has overridden the NPM main repo setting (pointing it to the HPE site?). No idea. I can't debug a Windows installation to which I don't have access. Otherwise, please see https://github.com/sinonjs/nise/issues/64#issuecomment-419221001

@promosjotte are you also running Windows? We need to find what is in common. Usually, issues like this are fixed by removing `node_modules` and running `npm install` again. None of our builds have failed due to this, but two reports on the same issue might point to a Windows issue, if that is a common nominator.

**Comment by fatso83** [comment] 2018-09-06 20:11
Also, the both of you; have you tried removing `node_modules` and reinstalling?

**Comment by fatso83** [comment] 2018-09-06 21:41
OK, tried this on a fresh Windows Server 2016 install. No problems. Installed with flying colors. Closed as cannot reproduce. I would inspect your local machines and/or any overrides for NPM registries. Try to redo the steps in a non-corporate environment, with a clean slate (`mkdir tmp; cd tmp; npm init; npm i nise;`)

**Closed by fatso83** 2018-09-06 21:41 UTC
Labels: Awaiting Response, Unverified

**Comment by arankhem** [comment] 2018-09-07 05:02
Can you remove that hpe link please i posted here by mistake. I have updated the link in my comment

**Comment by mroderick** [comment] 2018-09-07 05:04
I have edited @fatso83's comment to remove the link
