### ISSUE TITLE
Expectations on event handlers never met on object methods

### ISSUE THREAD

**Issue by ozzyogkush** [sinonjs/sinon#1536] opened 2017-08-17 21:22 UTC
* Sinon version(s) : 2.3.1, 3.2.1
* Environment   : NodeJS 6.10.0 on OSX El Capitan
* Other libraries you are using: grunt, react, mocha, chai, babel-register, babel-plugin-transform-class-properties

**What did you expect to happen?**

When I mock an object with a method that is used as an event handler callback for an EventEmitter (or a JSX element's onClick/etc event), and put expectations on the method, that the expectations work.

**What actually happens**

The method is not mocked, gets called, and the expectation is unmet.

**How to reproduce**

```js
const sinon = require('sinon');
import EventEmitter from 'events';

class X {
  constructor() {
     this.eventEmitter = new EventEmitter();
     this.eventEmitter.on('test', this.testHandler);
  }

  testHandler = () => {
    console.log(this);
    console.log('testHandler() called');
    this.additionalMethod();
  };
}

describe('test', function() {
  it('works', function() {
    const xObj = new X();
    const xObjMock = sinon.mock(xObj);

    xObjMock.expects('testHandler').once();
    xObj.eventEmitter.emit('test');
    xObjMock.verify(); // fails
  });
});
```

The above test would see the following in the console because the handler is actually called.

```js
X {
  eventHandler: [Object],
  testHandler: [Function]
}
testHandler() called

1) test works:
    ExpectationError: Expected testHandler([...]) once (never called)
```

I've experienced the same results when using events on React JSX elements as well (using event handlers like 

```<button onClick={this.clickHandler}>...</button>```

Any expectation on `clickHandler` never gets met.

**Comment by ozzyogkush** [comment] 2017-08-17 21:44
Normally I would simply test the behavior of the object and check the state of the object after calling `emit('test')` but in this case there are other considerations and I just want to verify that the proper event handler is being called.

**Comment by NewkirkS** [comment] 2017-10-03 16:19
Having the same issue using Sinon 4.0 when testing Vue 2 components. Interested to see any developments on this.

**Comment by mroderick** [comment] 2017-10-04 08:26
> Interested to see any developments on this.

I suspect that source of the issues is binding of context (`this`) when the mock is created. Whether it can be solved or we can find a workaround is another matter.

A PR for a solution or a failing test for [`issues-test.js`](https://github.com/sinonjs/sinon/blob/master/test/issues/issues-test.js) would be most welcome.

**Comment by rgroothuijsen** [comment] 2017-10-28 15:28
[According to the EventEmitter documentation](https://nodejs.org/api/events.html#events_passing_arguments_and_this_to_listeners) , EventEmitter makes "this" refer to itself rather than the object where it's used. The end result is that the function is called from another object than the one that Sinon is looking at. The documentation's suggested workaround is using arrow functions, i.e. () => { this.testHandler(); } This causes the expectation to be met.

**Comment by mroderick** [comment] 2017-10-29 08:59
@rgroothuijsen thank you for the clarification! Seeing as this is intended behaviour by `EventEmitter`, I am closing this issue.

**Closed by mroderick** 2017-10-29 08:59 UTC
Labels: Help wanted, Needs investigation

**Comment by mroderick** [comment] 2017-10-29 09:00
@NewkirkS if you are still seeing unexpected behaviour with 'sinon@4` and `vue`, please create a new issue for it. Please include a runnable example of how Sinon fails to meet expectations.
