### ISSUE TITLE
Stubbed getter called on restoring

### ISSUE THREAD

**Issue by micheleDiSalvatoreLoveholidays** [sinonjs/sinon#1177] opened 2016-11-03 10:29 UTC
Hi guys, I'm having an issue when I stub a getter. As I've seen [here](https://github.com/sinonjs/sinon/issues/897), it should work, but it could be that I'm not stubbing in the right way. 

Sinon version:
```log
$ npm list | grep 'sinon'
+-- karma-chai-sinon@0.1.5
+-- karma-sinon@1.0.5
+-- sinon@1.17.5
+-- sinon-chai@2.8.0
```

This is the code to test
```javascript
// stateHandlers.js
export default {
  get totalPrice() {
    console.log('totalPrice called');
    return 3;
  },

  get totalWasPrice() {
    console.log('totalWasPrice called');
    return 5;
  },

  get totalSaving() {
    return this.totalWasPrice - this.totalPrice;
  },
}
``` 

this is the test
```javascript
// __test__/stateHandlers.spec.js
import stateHandlers from '../stateHandlers';

describe('stateHandlers', function () {
  describe('#get totalSaving', function () {
    beforeEach(function () {
      console.log('stubbing');
      this.totalWasPriceStub = sinon.stub(stateHandlers, 'totalWasPrice', { get: () => 5 });
      this.totalPriceStub = sinon.stub(stateHandlers, 'totalPrice', { get: () => 3 });
      console.log('stubbed');
    });

    afterEach(function () {
      console.log('restoring');
      this.totalWasPriceStub.restore();
      this.totalPriceStub.restore();
      console.log('restored');
    });

    it('returns the right value', function () {
      console.log('running');
      expect(stateHandlers.totalSaving).to.equal(2);
      console.log('run');
    });
  });
});
```

```log
LOG: 'stubbing'
LOG: 'stubbed'
LOG: 'running'
LOG: 'run'
LOG: 'restoring'
LOG: 'totalWasPrice called'
LOG: 'totalPrice called'
LOG: 'restored'
```

**Comment by mroderick** [comment] 2016-11-09 11:18
> Hi guys, I'm having an issue when I stub a getter. As I've seen here, it should work, but it could be that I'm not stubbing in the right way.

What did you expect to happen? What is "should work" to you?

What actually happens? How can I see this failing for myself?

**Comment by micheleDiSalvatoreLoveholidays** [comment] 2016-11-14 11:30
I'm expecting that these logs are not showed 
```bash
LOG: 'totalWasPrice called'
LOG: 'totalPrice called'
```

**Comment by mroderick** [comment] 2016-11-14 14:54
This is a duplicate of https://github.com/sinonjs/sinon/issues/1124, which has a thorough explanation of the root cause and a suggestion for a solution.

I am closing this issue, please contribute to https://github.com/sinonjs/sinon/issues/1124.

**Closed by mroderick** 2016-11-14 14:54 UTC
Labels: Duplicate
