### ISSUE TITLE
sinon-2.0.0-pre.js not found in v1.17.5

### ISSUE THREAD

**Issue by rooskienz** [sinonjs/sinon#1112] opened 2016-07-26 23:12 UTC
Hi,

not sure if this has been addressed yet but after the release of 1.17.5 I'm getting this error when running tests:

Module not found: Error: Cannot resolve 'file' or 'directory' ..../node_modules/sinon/pkg/sinon-2.0.0-pre.js

* version 1.17.5

Cheers

**Comment by fatso83** [comment] 2016-07-26 23:26
If the pre-release of version 2.0.0 was shipped with v1.17.4 (which could have happened since the release scripts did not delete the `pkg` directory in between builds) that would be unintentional. Anyway, relying on another version of Sinon than what is in your `package.json` is ... unconventional :) If you do need version 2 (which is as of yet just available as a pre-release), try `npm install sinon@next --save-dev`.

Other than that, is is impossible to reproduce whatever error message you are getting since you have given absolutely no info on how to reproduce it. Closing.

**Closed by fatso83** 2016-07-26 23:26 UTC
