### ISSUE TITLE
Verbose test output

### ISSUE THREAD

**Issue by danihodovic** [sinonjs/sinon#904] opened 2015-10-27 17:16 UTC
I have a sinon.assertion that fails. It prints that the assertion failed and what the expected outcome was, but never what the actual test stub was called with. Is there a special flag to enable this?

``` javascript
sinon.assert.calledWith(this.setStub, {'en-US': undefined, 'de-DE': 'baz'})
```

**Comment by fatso83** [comment] 2015-10-28 09:14
From the [Contributing docs](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue):
To save everyone time and make it much more likely for your issue to be understood, worked on and resolved quickly, it would help if you're mindful of [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) when pressing the "Submit new issue" button.

As a minimum, please report the following:

**Which environment are you using? Browser? Node? Which version(s)?
Which version of SinonJS?**
How are you loading SinonJS?
What other libraries are you using?
What you expected to happen
What actually happens
Describe with code how to reproduce the faulty behaviour

**Comment by jonnyt886** [comment] 2017-03-14 12:07
Hi there, +1 on this. I run my tests via `npm test` and get assertion failures but no additional info. It'd be helpful for Sinon to output what stubs were called & their arguments.

I run Sinon with Buster.js, via:
`buster.testCase("...", { 
    "my test" : function() {
        var fakeStream = {};
        this.stub(fs, "createReadStream").returns(fakeStream);

        // ....

        // I expect createReadStream() to be called several times with different
        // filenames each time, and want to assert each one
        for (f in filenames) {
            assert(fs.createReadStream.calledWith(path.join(directory, filenames[f]));
        }
    }
`

Node v6.9.2
BusterJS v0.7.18
Sinon-buster 0.5.0
Sinon 1.9.1

**Comment by mantoni** [comment] 2017-03-14 14:01
@jonnyt886 You have to use the `sinon.assert` library for this to work. In your case, the boolean comparison in `assert` is failing. There is no way we can intercept this.

I cannot reproduce the issue and no additional details where provided for more than a year. Closing.

**Closed by mantoni** 2017-03-14 14:01 UTC
