### ISSUE TITLE
Fake server does not provide response body upon returning error response

### ISSUE THREAD

**Issue by ivawzh** [sinonjs/sinon#1057] opened 2016-06-03 06:08 UTC
Hi, I was trying to test error handling in my code. Found out that fake server doesn't return anything in response body if a HTTP status code is anything between 400 ~ 599. My question is WHY!!! And what should I do to test situations like handling validation error messages upon failing CREATE request .

```
describe.only('sinon fakeserver does not give response body upon error', () => {
  let response
  beforeEach(() => {
    response = 'waaaaa'
    const server = sinon.fakeServer.create({ respondImmediately: true })
    server.respondWith(
      'PUT',
      '/dummyurl',
      [422, { 'Content-Type': 'application/json' }, response]
    )
  })

  it('will get body?', done => {
    require('jquery').ajax({
      method: 'PUT',
      url: '/dummyurl',
      contentType: 'application/json; charset=UTF-8',
      data: {
        whatever: {}
      },
      dataType: 'json'
    }).then(
      () => {},
      (error) => {
        expect(error).to.exist
        expect(error.responseText).to.eq(response)
        done()
      }
    )
  })
})
```

Result:
```
AssertionError: expected undefined to equal 'waaaaa'
```

**Comment by fatso83** [comment] 2016-06-04 07:04
Jquery might be obscuring what is really happening. Could you try replacing it with a normal Xhr call? Fully might be a bug, related to changes introduced in 1.17.4, so you could also try changing the version to 1.17.3.

**Comment by ThinTim** [comment] 2016-06-08 01:18
This is probably a duplicate of #1040

**Comment by fearphage** [comment] 2016-07-16 15:43
@ThinTim I believe you are correct. Closing as dupe.

**Closed by fearphage** 2016-07-16 15:43 UTC

**Comment by ivawzh** [comment] 2016-07-24 22:38
Sorry to reply late. Looks like the problem of https://github.com/sinonjs/sinon/issues/1040 is that Ajax error handler is not triggered. However, in my environment, it actually does trigger error handler. Just the `responseText` is missing as `undefined`.

**Comment by MatthewKosloski** [comment] 2016-10-16 00:35
doesn't work with Mocha:

	Error: Expected false to exist
	at assert (node_modules/expect/lib/assert.js:29:9)
	at Expectation.toExist (node_modules/expect/lib/Expectation.js:52:28)
	at Context.<anonymous> (test/components/Foo.spec.js:39:35)

**Comment by mjaveddd** [comment] 2018-01-12 20:29
Should this be re-opened since the issue is not a dupe? 

Was there any solution discovered for this? @ivawzh

**Comment by mroderick** [comment] 2018-01-13 12:35
@mjaveddd if you think this issue still exists in recent releases, it would be great if you could open a new GitHub issue for it with a reduced test case that demonstrates it
