### ISSUE TITLE
useFakeTimers with typescript

### ISSUE THREAD

**Issue by aboeglin** [sinonjs/sinon#1740] opened 2018-03-20 08:13 UTC
I try to make an es6 project move to typescript. It's still pretty small at the moment. In the current test file there are no dependencies except the test file, chai and mocha.

I import sinon like this:
```javascript
import * as sinon from 'sinon';
```
But it then throws at me when running the tests:
```javascript
TypeError: Cannot read property 'now' of undefined
        at mirrorDateProperties (base/test/SESKApplication.test.js?cbd5a7d2db216d155cbf259dccb4fc057a6c807d:23248:16)
        at hijackMethod (base/test/SESKApplication.test.js?cbd5a7d2db216d155cbf259dccb4fc057a6c807d:23522:20)
        at Object.install (base/test/SESKApplication.test.js?cbd5a7d2db216d155cbf259dccb4fc057a6c807d:23793:13)
        at Object.exports.useFakeTimers (base/test/SESKApplication.test.js?cbd5a7d2db216d155cbf259dccb4fc057a6c807d:11686:21)
        at Context.<anonymous> (base/test/SESKApplication.test.js?cbd5a7d2db216d155cbf259dccb4fc057a6c807d:30655:21)
```

Everything else works just fine. It's only useFakeTimers which seems to be a little brittle somehow. I even tried to install types for lolex just in case, but that did not solve the issue.

* Sinon version : 5.0.0-next.3 ( tried 4.3 originally with the same issue )
* Environment   : OSX 10.13.3
* Other libraries you are using: Mocha, Karma, Chai, Typescript 2.6

**Comment by mroderick** [comment] 2018-03-27 06:29
@aboeglin did you find a solution to this problem?

**Comment by fatso83** [comment] 2018-03-27 15:20
Whatever the reason is for this problem, it is highly likely to have nothing to do with TypeScript per se. `Date` is undefined for some reason, and as this problem is unreproducible without supporting code I am closing this.

**Closed by fatso83** 2018-03-27 15:20 UTC

**Comment by iraklisg** [comment] 2018-06-26 10:00
I am facing the same problem after upgrading from `sinon@4.4.6` to `sinon@6.0.1`

I made a silly little test to showcase the issue:
```
describe('Countdown', () => {
    it('should works', () => {
            const clock = sinon.useFakeTimers();
            expect(clock).to.be.an.instanceOf(Object);
    });
});
```
The test will fail with the following errors:
> 1) Countdown
>        should works:
>      TypeError: Cannot read property 'now' of undefined
>       at mirrorDateProperties (.tmp/mocha-webpack/1530006960272/bundle.js:53971:20)
>       at hijackMethod (.tmp/mocha-webpack/1530006960272/bundle.js:54274:24)
>       at Object.install (.tmp/mocha-webpack/1530006960272/bundle.js:54664:17)
>       at useFakeTimers (.tmp/mocha-webpack/1530006960272/bundle.js:54712:23)
>       at Sandbox.useFakeTimers (.tmp/mocha-webpack/1530006960272/bundle.js:65700:47)
>       at Context.<anonymous> (.tmp/mocha-webpack/1530006960272/bundle.js:24018:76)

**Comment by fatso83** [comment] 2018-06-26 13:20
@iraklisg I cannot reproduce this locally or in [this online demo](https://runkit.com/fatso83/5b323cb556865c0012ba4368)

**Comment by iraklisg** [comment] 2018-07-12 08:21
@fatso83 sorry for the late reply, the issue is being reported also in #1852
