### ISSUE TITLE
Sandbox promise reset also clear promiseLibrary

### ISSUE THREAD

**Issue by immanuel192** [sinonjs/sinon#1765] opened 2018-04-14 18:42 UTC
* Sinon version : 2.3.6 - 4.5.0
* Environment   : any
* Example URL   : none
* Other libraries you are using: Bluebird

**What did you expect to happen?**
- Giving this code

```js
const promise = require('bluebird');
const sinon = require('sinon');

const sandbox = sinon.sandbox.create().usingPromise(promise);
const test = {
  test: {
    field1: sandbox.stub(),
    field2: sandbox.stub()
  }
};

test.test.field1.resolves('abc');
const t1 = test.test.field1();

sandbox.reset();
test.test.field1.resolves('abc');
const t2 = test.test.field1();

sandbox.reset();
sandbox.usingPromise(promise);
test.test.field1.resolves('abc');
const t3 = test.test.field1();

sandbox.reset();
test.test.field1.usingPromise(promise);
test.test.field1.resolves('abc');
const t4 = test.test.field1();
```
- First time resolve : sinon returns instance of Bluebird (const `t1`)
- After you call `sandbox.reset()`, sinon will clear everything, especially `promiseLibrary`. It means that sinon will resolves instance of Native ES6 Promise instead of Bluebird (const `t2`, `t3`)
- In order to play around to make it works again, we need to manually call `usingPromise` (const `t4`)

**What actually happens**
- Calling `sandbox`.`reset` will also remove `promiseLibrary`, even in `defaultBehaviour`

**How to reproduce**
- Check the code above

**Comment by fearphage** [comment] 2018-07-08 22:55
@immanuel192 You were very close. The issue is actually the line above it `this.defaultBehavior = null;`. The `promiseLibrary` information is stored on this property. When it's wiped out, the connection is broken. 

https://github.com/sinonjs/sinon/blob/c3a978a893bdf0279f455840af5172558c06633c/lib/sinon/behavior.js#L113-L115

**Comment by mroderick** [comment] 2018-07-09 06:09
With the current behaviour (`reset` resets everything), it is inconvenient and non-obvious to have to tell the sandbox about the promise implementation after each `reset`.

If we change the behaviour of `reset` to not touch promise preferences, we will alter the behaviour of people's tests in new and unexpected ways (invisible).

```js
// a.test.js
var promise = require('bluebird');
var sinon = require('sinon').usingPromise(promise);

describe('myModule', function() {
    afterEach(function(){
        sinon.reset();    
        // doesn't change promise preferences
    })
});

// b.test.js
// this test does not use bluebird, but is loaded after `a.test.js`
var sinon = require('sinon');
// surprise! the default sandbox is using bluebird
// because `b.test.js` was loaded after `a.test.js`
// and reset doesn't remove promise preferences
```

Here's a solution that could address both concerns

* Replace `usePromise` on the default sandbox with a method that throws an `Error` saying that `usePromise` cannot be used on the default sandbox and that you should create a sandbox with `createSandbox`.
* Change `reset` to not wipe promise implementation preferences

This change of behaviour should be in a `MAJOR` release.

What do you think @immanuel192 @fearphage?

**Comment by immanuel192** [comment] 2018-08-04 03:44
@mroderick Here is my current code to solve the problem.

```js
export const newSandbox = () => {
  const sandbox = sinon.sandbox.create()
    .usingPromise(Promise);

  //
  sandbox.reset_ = sandbox.reset.bind(sandbox);
  sandbox.reset = () => {
    sandbox.reset_();
    for (const fake of (sandbox.fakes || [])) {
      fake.usingPromise && fake.usingPromise(Promise);
    }
  };
  return sandbox;
};
```

**Comment by fearphage** [comment] 2018-08-04 04:07
@immanuel192 FYI if you overwrite the global `Promise` (as it appears you have in the code above), you don't need to do any of this. Sinon uses the global `Promise` by default.

`global.Promise = require('bluebird');`

**Comment by immanuel192** [comment] 2018-08-04 06:10
@fearphage thanks. From my understanding, it will also override native Promise which may coz concerns and not very good for all cases. What do you think?

**Comment by fearphage** [comment] 2018-08-04 06:15
> it will also override native Promise which may coz concerns and not very good for all cases.

I have no idea about adverse outcomes from overwriting the global promise. They may exist, but I just don't know about them personally.

**Comment by immanuel192** [comment] 2018-08-04 09:43
@mroderick I prefer to change behaviour of `reset` in sandbox. When reset a sandbox, it should not remove the registered Promise

**Comment by fatso83** [comment] 2024-09-10 22:32
Closing as no one has provided a PR and this seems like a feature that is no longer wanted in 2024

**Closed by fatso83** 2024-09-10 22:32 UTC
Labels: pinned
