### ISSUE TITLE
Restoring stubbed node modules with Sinon 1.17.2 does not work

### ISSUE THREAD

**Issue by medialwerk** [sinonjs/sinon#965] opened 2016-01-15 11:35 UTC
## Environment

    Node v5.1.1
    Sinon 1.17.2
    CoffeeScript 1.10.0 (i guess its unimportant)

## Test Case

```coffeescript
describe.only 'SinonTestCase', ->
  sinonTestCase = null

  beforeEach ->
    sandbox = sinon.sandbox.create()
    sinonTestCase = require './sinon_test_case.server'
    console.log sinonTestCase.init.restore?
    sandbox.stub sinonTestCase
    console.log sinonTestCase.init.restore?

  afterEach ->
    sandbox.restore()
    console.log sinonTestCase.init.restore?


  it 'should work', ->
    expect(true).to.be.true
```

```coffeescript
module.exports =
  init: ->
    console.log 'Hello World'
```

## Expected result

```bash
info: [mongodb_adapter.coffee#null:105] MongoDB: Connected
  SinonTestCase
false
true
    ✓ should work
false
```

## Actual result

```bash
info: [mongodb_adapter.coffee#null:105] MongoDB: Connected
  SinonTestCase
false
true
    ✓ should work
true
```

## More info:

    I updated sinon from version 1.16.1 to 1.17.2. Sinon 1.16.1 restores the modules correctly.

Thanks! :-)

**Comment by jonnyreeves** [comment] 2016-01-16 19:05
Possible dupe of #947?

**Comment by fatso83** [comment] 2016-01-18 12:18
Thanks for reporting this. Good report with enough detail! This looks like something we should look into.

@jonnyreeves : it does look related, so possibly, but it's hard to be sure without digging further into it. I guess a fix for this issue should also see if it fixes the other bug.

**Comment by lucasfcosta** [comment] 2016-06-23 20:39
Is this still an issue?

I just tested it here and everything seems to be working fine.

I added this test to the `sandbox-test.js` file:
```js
describe.only("restores stubbed modules", function () {
    var sinonTestCase = null;
    var sandbox = sinon.sandbox.create();

    beforeEach(function() {
        sinonTestCase = require('./testModule');
        console.log(Boolean(sinonTestCase.init.restore));
        sandbox.stub(sinonTestCase);
        console.log(Boolean(sinonTestCase.init.restore));
    });

    afterEach(function() {
        sandbox.restore();
        console.log(Boolean(sinonTestCase.init.restore));
    });

    it('should work', function() {
        assert(true);
    });

});
```

And I have also created this module to stub:
```js
module.exports = {
    init: function() { console.log('Hello World')}
};
```

**And then I got this output:**
```js
  sinon.sandbox
    configurable sandbox
      restores stubbed modules
false
true
        ✓ should work
false
```

Am I missing something here?

**Comment by fatso83** [comment] 2016-06-29 11:51
As @lucasfcosta research seems to imply that this is no longer issue, I am closing this. If @medialwerk find that there is still an issue here, just reopen the case, but please supply a full working example as `./sinon_test_case.server'` is not available for inspection.

**Comment by fatso83** [comment] 2016-06-29 11:53
Ah, crap. I just noticed the 1.x label  😊. @lucasfcosta's tests were against the `master` branch. Reopening for inspection.

**Comment by fatso83** [comment] 2016-06-29 13:32
I just ran the test case supplied by @lucasfcosta against the `v1.17` branch. Getting the expected results, so I am closing this.

**Closed by fatso83** 2016-06-29 13:32 UTC
Labels: 1.x, Bug, Help wanted, Needs investigation
