### ISSUE TITLE
Stubbing, and restoring do not work with es6 class instances

### ISSUE THREAD

**Issue by autoric** [sinonjs/sinon#878] opened 2015-10-14 18:04 UTC
### Environment: 
 - Node 4.2.1
 - Sinon 1.15.4
 - Writing natively supported es6 syntax, no transpilers.

### Test Case:
```
'use strict';
const sinon = require('sinon');

class C {
  foo(){ }
}

const c = new C();

const sandbox = sinon.sandbox.create();

sandbox.stub(c);
sandbox.restore();
sandbox.stub(c);
sandbox.restore();
```

### Expected result:
No errors, code executes and exists cleanly.

### Actual results:
```
TypeError: Attempted to wrap foo which is already wrapped
    at checkWrappedMethod (/Users/erin.noe-payne/local/lr-zmq/node_modules/sinon/lib/sinon/util/core.js:81:29)
    at Object.wrapMethod (/Users/erin.noe-payne/local/lr-zmq/node_modules/sinon/lib/sinon/util/core.js:121:21)
    at stub (/Users/erin.noe-payne/local/lr-zmq/node_modules/sinon/lib/sinon/stub.js:67:26)
    at /Users/erin.noe-payne/local/lr-zmq/node_modules/sinon/lib/sinon/stub.js:60:25
    at /Users/erin.noe-payne/local/lr-zmq/node_modules/sinon/lib/sinon/walk.js:26:26
    at Array.forEach (native)
    at walkInternal (/Users/erin.noe-payne/local/lr-zmq/node_modules/sinon/lib/sinon/walk.js:23:45)
    at Object.walk (/Users/erin.noe-payne/local/lr-zmq/node_modules/sinon/lib/sinon/walk.js:46:20)
    at Object.stub (/Users/erin.noe-payne/local/lr-zmq/node_modules/sinon/lib/sinon/stub.js:52:23)
    at Object.stub (/Users/erin.noe-payne/local/lr-zmq/node_modules/sinon/lib/sinon/collection.js:106:49)
```

### More info:
 - Manually stubbing and restoring each function does work: `sinon.stub(c, 'foo'); c.foo.restore();`
 - Using `sinon.stub` and `sinon.restore` instead of sandboxes does not work - it fails with the same issue, I assume with the same root cause

**Comment by mantoni** [comment] 2015-10-14 19:17
Please upgrade to the latest Sinon 1.17 where this should work.

**Comment by autoric** [comment] 2015-10-14 19:28
It does not work in 1.17. I'm actually using 1.17.1 - I misread my package.json.

You can run the provided code in the latest sinon and observe the issue.

**Comment by mantoni** [comment] 2015-10-16 16:33
I noticed that https://github.com/sinonjs/sinon/pull/870 did not make it into a release yet. We need to cut `1.17.2` to ship this fix. @mroderick Can I ask you to do that release? I still didn't look into how the release process works now :grimacing:

**Comment by mroderick** [comment] 2015-10-16 17:33
Sure, I can look into that this weekend

**Comment by mroderick** [comment] 2015-10-21 15:45
`sinon@1.17.2` is now published to npm

@autoric would you mind testing with that version?

**Comment by autoric** [comment] 2015-10-21 18:50
Will integrate and test today. Thanks a lot for the support!

**Comment by autoric** [comment] 2015-10-22 01:06
@mroderick I see no change with the issue in my production code. 

Further, running the simple test case provided for this issue continues to throw the same error. Did you see it run successfully?

**Comment by amalahussein** [comment] 2015-10-23 04:50
Same here....same issue for me as well with es6.

**Comment by jedverity** [comment] 2015-12-01 02:14
+1

**Comment by fatso83** [comment] 2015-12-02 09:01
For everyone experiencing this you should help us out and try our pre-release of Sinon 2. We regard it as quite ready, but there might be things we haven't been able to see yet that's lurking beneath the surface. Try it out like this:
```
npm install sinon@next
```
... and use the issue tracker for any issues you come across.

**Comment by glortho** [comment] 2015-12-02 14:15
Great will do @fatso83 . I take it existing API will mostly apply in next. If not do you have v2 docs somewhere?

**Comment by fatso83** [comment] 2015-12-02 15:08
All current development on `master` is for version 2. 1.x is in maintenance mode. The API will be mostly kept, except for a few breaking changes documented in the issue tracker (don't remember the issue on the top of my head).

**Comment by fatso83** [comment] 2016-02-10 09:59
@mantoni We have no fix for this in `master`: the bug is still there, so this must be something else than #867/#868. I pasted the test script above into `878-test.js` and ran `node 878-test.js`. Got the exact same error as in the case description.

**Comment by symposion** [comment] 2016-04-20 17:30
Hey, Just ran into this issue. Could perhaps be related to the fact that ES6 class methods are not enumerable and thus don't show up in for...in etc?

**Comment by Menda** [comment] 2016-06-02 11:19
For version `2.0.0` it's possible to stub ES2016 classes. Here there is a post about how to make it:
https://eirikardal.no/stubbing-es2015-classes-with-sinon/

**Comment by fatso83** [comment] 2016-06-02 16:45
@Menda You are mistaking this bug for something else :-) This post is about stubbing _instances_ of a class, not the class itself. Stubbing ES6 classes has been covered extensively before (see [#831](https://github.com/sinonjs/sinon/issues/831#issuecomment-209648966) and #1035). So for latecomers wanting to know about that, please [read and understand this thread](https://github.com/sinonjs/sinon/issues/831) on a similar issue. It might shed some light on what you are trying to do. 

The thread basically says the same as the article, which by the way has _nothing_ to do with Sinon 2.0. Spying and stubbing ES6 classes is equally possible (and impossible - depending on what you want to do) with Sinon 1.x. Read [my comment](https://github.com/sinonjs/sinon/issues/831#issuecomment-209648966) if you want a concise summary of how to do various things in ES6, including examples with code.

**Comment by Menda** [comment] 2016-06-02 18:29
Thanks @fatso83. I totally mixed up things, my bad!

**Comment by franvarney** [comment] 2016-07-22 03:40
I just want to confirm v2/next solves the "Attempted to wrap.." error for me!

**Comment by davidtzoor** [comment] 2016-09-28 14:37
@fatso83 I didn't understand if there is a way to stub an ES6 class method, and still having the same issue (BTW, I can't seem to find sinon v2 anywhere...)

**Comment by fatso83** [comment] 2016-09-28 15:15
@davidtzoor There is nothing special about an ES6 class compared to an ES5 class. It's just syntactic sugar. You still have the prototype _object_. Stub instance methods any way you would with an ES5 class.

```javascript
class FooClass{
  static classMethod(){}
  instanceMethod(){}
}
```

is nothing but this
```javascript
function FooClass(){}
FooClass.classMethod = function(){}
FooClass.prototype.instanceMethod = function(){}
```

So if you want to stub class methods just stub methods on the class object and not on the instances:
```javascript
const stub = sinon.stub(FooClass, 'classMethod').returns('mystub');
```

**Comment by JoeChapman** [comment] 2016-10-06 15:52
I couldn't get that to work

**Comment by fatso83** [comment] 2016-10-06 17:19
Closed by mistake, sorry.

**Comment by lucasfcosta** [comment] 2016-10-06 18:45
I just tested this at the `master` branch with the exact same example described on the first post and the test passed. I'm not sure if I'm doing this on the wrong branch but this is the code I ran:

```js
it.only("should work with ES6 classes", function () {
    class C {
      foo(){ }
    }

    const c = new C();

    const sandbox = sinonSandbox.create();

    sandbox.stub(c);
    sandbox.restore();
    sandbox.stub(c);
    sandbox.restore();
});
```

And it seems to be running without problems.

**Comment by fatso83** [comment] 2016-10-06 21:10
@lucasfcosta, thank you for taking the time to check that out! Closing this as fixed.

**Comment by fatso83** [comment] 2016-10-06 21:11
@JoeChapman, try the mailing list or the Gitter chat room.

**Comment by davidtzoor** [comment] 2016-10-06 21:14
@lucasfcosta did you also test stubbing a method of an existing class instance?

**Comment by fatso83** [comment] 2016-10-06 21:22
@davidtzoor I know you asked how to do that earlier, so are the steps outlined failing to work somehow?

**Comment by davidtzoor** [comment] 2016-10-06 21:24
I am actually on a vacation, so can't check right now :) was wondering if
you already checked that. Will do next week, thanks

**Comment by fatso83** [comment] 2016-10-07 04:46
It's working. Stubbing a function property is the most basic use case for Sinon. Calling it a staric class

**Comment by coolnalu** [comment] 2016-10-21 02:06
Encountered this issue today. The exact code works for all tests except in one file. driving me nuts. lol. will try to create a test case to reproduce.

**Closed** 2016-10-21 05:40 UTC
Labels: 1.x, 2.x, Difficulty: Medium, Help wanted, Needs investigation

**Comment by fatso83** [comment] 2016-10-21 05:45
Think I mistakenly reopened this without noticing when commenting  a few weeks ago.
