### ISSUE TITLE
Stub document object

### ISSUE THREAD

**Issue by acampositrs** [sinonjs/sinon#1047] opened 2016-05-19 09:37 UTC
> When I try to stub the document object I get a exeption: TypeError: Cannot stub non-existent own property documentElement 

* Sinon version : 1.17.3

**What did you expect to happen?**
Stub document object

**What actually happens**
TypeError: Cannot stub non-existent own property documentElement 

**How to reproduce**
* Function to mock
```
function isElementInViewport(el) {

        //special bonus for those using jQuery
        if (typeof jQuery === "function" && el instanceof jQuery) {
            el = el[0];
        }

        var rect = el.getBoundingClientRect();

        return (
            rect.top >= 0 &&
            rect.left >= 0 &&
            rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) && /*or $(window).height() */
            rect.right <= (window.innerWidth || document.documentElement.clientWidth) /*or $(window).width() */
        );
    }
```

* My test
```

    describe.only('isElementInViewport(el)', function () {

        let windowInnerHeightSandbox,
            windowInnerWidthSandbox,
            element = jQuery('<div>');

        beforeEach(function () {

            windowInnerHeightSandbox = sinon.sandbox.create();

            windowInnerWidthSandbox = sinon.sandbox.create();

        });

        afterEach(function () {

            windowInnerHeightSandbox = sinon.sandbox.create();

            windowInnerWidthSandbox = sinon.sandbox.create();

        });

        after(function () {
            windowInnerHeightSandbox.restore();
            windowInnerWidthSandbox.restore();
        });

        it('View should include element (env with document)', () => {

            windowInnerWidthSandbox.stub(window, "innerWidth", undefined);

            windowInnerHeightSandbox.stub(document.documentElement, "clientHeight", 900); /* This makes a exception Error*/

            element[0].getBoundingClientRect = function(){
                return {
                    top: 0,
                    left: 0,
                    bottom: 400,
                    right: 400
                };
            };

            expect(service.isElementInViewport(element)).to.equal(true);

        });


    });
```
* Console output:
```
START:
LOG: 900
  unit/services/util_serv
    isElementInViewport(el)
      ✔ View should include element (env with window)
      ✖ View should include element (env with document)
LOG: 900
      ✔ View do not should include element (env with window)

Finished in 0.08 secs / 0.005 secs

SUMMARY:
✔ 2 tests completed
✖ 1 test failed

FAILED TESTS:
  unit/services/util_serv
    isElementInViewport(el)
      ✖ View should include element (env with document)
        Chrome 50.0.2661 (Linux 0.0.0)
      TypeError: Cannot stub non-existent own property documentElement
          at Object.stub (/home/acampos/dev/projts/valo-solutions-ikabo-2/node_modules/sinon/pkg/sinon.js:4182:35)
          at Context.<anonymous> (/tmp/cc0713c1ca57cccc2518a8cfaf019a66.browserify:94159:38 <- tests/unit/src/services/util.es6:207:37)

```

**Comment by fearphage** [comment] 2016-05-24 20:24
A few things that may help although I'm not sure they will solve the problem:

1. Don't use local variables across tests. Use the internal context for mocha (`this`).
1. Use only a single sandbox.

Result: 

```js
beforeEach(function() {
  this.sinon = sinon.sandbox.create();
  this.element = $(elem);
});

afterEach(function() {
  this.sinon.restore();
});

it(function() {
  var stub1 = this.sinon.stub(...);
});
```

Again that may not solve your issue, but they are good ideas just the same.

**Comment by fearphage** [comment] 2016-05-24 20:26
Also looking more at your tests, you're trying to stub properties. `spy` and `stub` are for stubbing functions and methods. You can may be able to override those values with getters and setters although I'm not sure if that's allowed. I'm going to close this for now as it is not a bug.

**Closed by fearphage** 2016-05-24 20:26 UTC
